### ISSUE TITLE
Python udiskie error

### ISSUE THREAD

**Issue by mikebaum1** [coldfix/udiskie#100]
After following the udiskie installation instructions at https://github.com/coldfix/udiskie/wiki/Ubuntu-Debian-installation-guide, I get NameMount error. I enter the Python command udiskie-mount /dev/sdb1 --force and get back an error NameError: name 'mount' is not defined

**Comment by coldfix** [comment]
Hey,

thanks for making the effort to report this problem. Can you please post the full program output (in both cases)?

**Comment by mikebaum1** [comment]
>>> udiskie-mount /dev/sdb1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'mount' is not defined

**Comment by coldfix** [comment]
Is this in your python shell?

Please execute the command from your normal shell.

**Comment by mikebaum1** [comment]
yes, I am running it in my Python shell. I can do this with the mount cmnd in linux and it works fine.
I ran it in linux shell and get
root@mike1:/# udiskie-mount /dev/sdb1
not mounting /org/freedesktop/UDisks2/block_devices/sdb1: unhandled device
root@mike1:/#

**Comment by coldfix** [comment]
First: please execute udiskie in user mode, there is no reason to run it as root (then you could just use normal mount tool).

Second: Is your `sdb1` device an internal device? By default, udiskie handles only external devices. To see why udiskie decided not to mount your device, you can enter `udiskie-mount -v /dev/sdb1` and post the program output. Also, please show the output of `udisksctl info -b /dev/sdb1`. The default handling options can be changed by creating a config file (I'll show you, as soon as I see the problem).

**Comment by mikebaum1** [comment]
perhaps i am using udiskie incorrectly. I want to be able to mount and
unmount scsi hard drives from a Python program.I need to mount ans unmount
many drives often. i don't want to use the typical Python functions that
shell out to bash. Can  I use udiskie from a python program?

On Mon, Jan 25, 2016 at 11:03 AM, Thomas G. <notifications@github.com>
wrote:

> First: please execute udiskie in user mode, there is no reason to run it
> as root (then you could just use normal mount tool).
>
> Second: Is your sdb1 device an internal device? By default, udiskie
> handles only external devices. To see why udiskie decided not to mount your
> device, you can enter udiskie-mount -v /dev/sdb1 and post the program
> output. Also, please show the output of udisksctl info -b /dev/sdb1. The
> default handling options can be changed by creating a config file (I'll
> show you, as soon as I see the problem).
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_coldfix_udiskie_issues_100-23issuecomment-2D174604465&d=CwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=5LWk3N5cxYJ0RyFU4KgsEsalITvn5mCef87Amb_rKDU&m=kppZxRCM9ZWv22BWgpvJS9TSykcOpTSQXHAvMFkbcLA&s=pJqQkbMdtifLipipgyCcPcJd5xKKoUC3ww934U1R1i8&e=>
> .
>



-- 
Regards

Mike Baum
office 720-684-1368
cell 303-818-1414

**Comment by coldfix** [comment]
I see. If you need a python library for device management rather than a command line tool udiskie is not your best fit. Primarily, udiskie is a program that allows users to manage devices from the command line (or stays in the background and automatically mounts).

You could directly use *udisks* instead like udiskie does too. udiskie uses a hand-written dbus-binding to udisks (to be able to use both udisks1 or udisks2) - but in your case it could be enough to use some existing wrapper like http://lazka.github.io/pgi-docs/index.html#UDisks-2.0 .

**Comment by mikebaum1** [comment]
I have been using udisks but was hoping to find a method to mount and unmount in Python and NOT use a bash command. Is there any way to mount / unmount internal sata or scsi hard drives from a Python script without shelling out to bash?

**Comment by coldfix** [comment]
Sure. Here using PyGI to access the DBus interface of UDisks2:

```
from gi.repository import Gio

proxy = Gio.DBusProxy.new_for_bus_sync(
    Gio.BusType.SYSTEM,
    Gio.DBusProxyFlags.NONE,
    info=None,
    name='org.freedesktop.UDisks2',
    object_path='/org/freedesktop/UDisks2/block_devices/sdb1',
    interface_name='org.freedesktop.UDisks2.Filesystem',
    cancellable=None,
)

proxy.Mount('(a{sv})', {})
proxy.Unmount('(a{sv})', {})
```

For more information, see

- the [UDisks2 documentation](http://udisks.freedesktop.org/docs/latest/) which defines the UDisks2 DBus interface
- the [PyGI Gio documentation](http://lazka.github.io/pgi-docs/index.html#Gio-2.0)
- the [PyGI UDisks2 binding](http://lazka.github.io/pgi-docs/index.html#UDisks-2.0) mentioned in the previous post, which you could use rather than writing your own DBus binding
- the udiskie source itself, for an example how to write an asynchronous client application. In particular, consider the modules `udiskie.dbus`, `udiskie.async`, `udiskie.udisks2`

I'll close this issue for now, as this doesn't seem to be udiskie related.

Best regards,
Thomas

**Comment by mikebaum1** [comment]
Thanks so much for your help on this!

On Mon, Jan 25, 2016 at 5:25 PM, Thomas G. <notifications@github.com> wrote:

> Sure. Here using PyGI to access the DBus interface of UDisks2:
>
> from gi.repository import Gio
>
> proxy = Gio.DBusProxy.new_for_bus_sync(
>     Gio.BusType.SYSTEM,
>     Gio.DBusProxyFlags.NONE,
>     info=None,
>     name='org.freedesktop.UDisks2',
>     object_path='/org/freedesktop/UDisks2/block_devices/sdb1',
>     interface_name='org.freedesktop.UDisks2.Filesystem',
>     cancellable=None,
> )
>
> proxy.Mount('(a{sv})', {})
> proxy.Unmount('(a{sv})', {})
>
> For more information, see
>
>    - the UDisks2 documentation
>    <https://urldefense.proofpoint.com/v2/url?u=http-3A__udisks.freedesktop.org_docs_latest_&d=CwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=5LWk3N5cxYJ0RyFU4KgsEsalITvn5mCef87Amb_rKDU&m=JEU9UlNABXPKxakwmRqz3z7e8QjIY8nbb6DPHjN7PXQ&s=Wlq6QYEl8MMtiyU4FLo2N35DS7epljuDrcm20sT5wOA&e=>
>    which defines the UDisks2 DBus interface
>    - the PyGI Gio documentation
>    <https://urldefense.proofpoint.com/v2/url?u=http-3A__lazka.github.io_pgi-2Ddocs_index.html-23Gio-2D2.0&d=CwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=5LWk3N5cxYJ0RyFU4KgsEsalITvn5mCef87Amb_rKDU&m=JEU9UlNABXPKxakwmRqz3z7e8QjIY8nbb6DPHjN7PXQ&s=F7hJkVGHX7EqwWakCpkE78POV9lJcRw7lSKNhKZNxO8&e=>
>    - the PyGI UDisks2 binding
>    <https://urldefense.proofpoint.com/v2/url?u=http-3A__lazka.github.io_pgi-2Ddocs_index.html-23UDisks-2D2.0&d=CwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=5LWk3N5cxYJ0RyFU4KgsEsalITvn5mCef87Amb_rKDU&m=JEU9UlNABXPKxakwmRqz3z7e8QjIY8nbb6DPHjN7PXQ&s=X-Dd5dVsLvXD7nFddEzPPst9XiZF2cdqsfjm2SY2pfM&e=>
>    mentioned in the previous post, which you could use rather than writing
>    your own DBus binding
>    - the udiskie source itself, for an example how to write an
>    asynchronous client application. In particular, consider the modules
>    udiskie.dbus, udiskie.async, udiskie.udisks2
>
> I'll close this issue for now, as this doesn't seem to be udiskie related.
>
> Best regards,
> Thomas
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_coldfix_udiskie_issues_100-23issuecomment-2D174744989&d=CwMCaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=5LWk3N5cxYJ0RyFU4KgsEsalITvn5mCef87Amb_rKDU&m=JEU9UlNABXPKxakwmRqz3z7e8QjIY8nbb6DPHjN7PXQ&s=qtmqZzFrFXz3PsjD8VCKvIBk-3cXU6TVPs-qFQ8Srbk&e=>
> .
>



-- 
Regards

Mike Baum
office 720-684-1368
cell 303-818-1414
