### ISSUE TITLE
Udiskie 1.4.7 requires X server

### ISSUE THREAD

**Issue by jasonwryan** [coldfix/udiskie#102]
If 1.4.7 is started from the TTY with the `NT` options, it fails with the following error:
```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/udiskie/cli.py", line 254, in _start_async_tasks
    yield self._init()
  File "/usr/lib/python3.5/site-packages/udiskie/cli.py", line 339, in _init
    prompt = udiskie.prompt.password(options['password_prompt'])
  File "/usr/lib/python3.5/site-packages/udiskie/prompt.py", line 173, in password
    return gui() or tty()
  File "/usr/lib/python3.5/site-packages/udiskie/prompt.py", line 170, in <lambda>
    gui = lambda: has_Gtk()          and get_password_gui
  File "/usr/lib/python3.5/site-packages/udiskie/depend.py", line 59, in has_Gtk
    return check_call((RuntimeError, ImportError), require_Gtk, min_version)
  File "/usr/lib/python3.5/site-packages/udiskie/common.py", line 38, in check_call
    func(*args)
  File "/usr/lib/python3.5/site-packages/udiskie/depend.py", line 43, in require_Gtk
    raise RuntimeError(_("X server not connected!"))
NameError: name '_' is not defined
```

Dwongrading to 1.3.2 throws this error, but udiskie happily backgrounds and mounts removable media:
```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
/usr/bin/udiskie:9: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  load_entry_point('udiskie==1.3.2', 'console_scripts', 'udiskie')()
```

I noticed this because my `systemd --user` service failed after updating; evidently because udiskie is looking for a (nonexistent) X server if I login to TTY, or it just hasn't started yet in X. Once X is running, issuing `systemctl --user restart usdiskie.service` starts it fine. But it shouldn't rely on X, should it?

**Comment by coldfix** [comment]
Hey, thanks for your report! I fixed the issue in the most recent commit and will upload a new version shortly.

**Comment by fmitha** [comment]
I just ran into this as well. I was trying to run `udiskie` inside cron. I'm running 1.4.9 here, and the problem is reproducible inside a cron script, at least. The line in question is:

    udiskie-mount -o umask=0022 /dev/disk/by-uuid/4E1AEA7B1AEA6007

**Comment by coldfix** [comment]
Hey, can you post the stack trace in your case?

**Comment by fmitha** [comment]
I'd be glad to. Can you give me instructions on how to do so? In my cron job I only get this:

    Unable to init server: Could not connect: Connection refused

**Comment by coldfix** [comment]
So far, this might be only a warning. Start udiskie with the `--verbose` flag and redirect all output to a log file, e.g.:

```
* * * * * udiskie-mount -o umask=0022 /dev/disk/by-uuid/4E1AEA7B1AEA6007 --verbose >~/udiskie-debug.log 2>&1
```

**Comment by fmitha** [comment]
Hi @coldfix, 

here's the debug ouput. Does it tell you anything?
```
DEBUG [2016-04-19 01:48:01,589] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/faheem/.config/udiskie/config.yml'
DEBUG [2016-04-19 01:48:01,591] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/faheem/.config/udiskie/config.json'
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
DEBUG [2016-04-19 01:48:01,816] udiskie.config: IgnoreDevice(match={'is_block': False}, value=True) created
DEBUG [2016-04-19 01:48:01,816] udiskie.config: IgnoreDevice(match={'is_external': False}, value=True) created
DEBUG [2016-04-19 01:48:01,816] udiskie.config: IgnoreDevice(match={'is_ignored': True}, value=True) created
DEBUG [2016-04-19 01:48:01,818] udiskie.udisks2: found device owning "/dev/disk/by-uuid/4E1AEA7B1AEA6007": "/org/freedesktop/UDisks2/block_devices/sde1"
INFO [2016-04-19 01:48:01,818] udiskie.mount: not mounting /org/freedesktop/UDisks2/block_devices/sde1: already mounted
```

**Comment by coldfix** [comment]
Can't see any error. In what way doesn't it behave as expected? Or are you just concerned by the message?

**Comment by fmitha** [comment]
On Mon, 18 Apr 2016, Thomas G. wrote:

> 
> Can't see any error. In what way doesn't it behave as expected? Or are 
> you just concerned by the message?

If the USB device is not already mounted, then it fails with an error, as 
follows. The output below is what I obtain from my actual cron script.

My bash script has `set -e`, so I'm not sure why the script does not exit 
immediately - it goes on to try to run `borg create`. Is udiskie not 
returning the right signal, perhaps?

The error seems to be the

     GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorizedCanObtain: Not
authorized to perform operation

                                                     Regards, Faheem Mitha

+ CLEVEL=zlib,9
+ udiskie-mount -o umask=0022 /dev/disk/by-uuid/4E1AEA7B1AEA6007 --verbose
DEBUG [2016-04-19 14:00:02,110] udiskie.config: Failed to read config 
file: [Errno 2] No such file or directory: 
'/home/faheem/.config/udiskie/config.yml'
DEBUG [2016-04-19 14:00:02,113] udiskie.config: Failed to read config 
file: [Errno 2] No such file or directory: 
'/home/faheem/.config/udiskie/config.json'
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
DEBUG [2016-04-19 14:00:02,339] udiskie.config: 
IgnoreDevice(match={'is_block': False}, value=True) created
DEBUG [2016-04-19 14:00:02,339] udiskie.config: 
IgnoreDevice(match={'is_external': False}, value=True) created
DEBUG [2016-04-19 14:00:02,339] udiskie.config: 
IgnoreDevice(match={'is_ignored': True}, value=True) created
DEBUG [2016-04-19 14:00:02,343] udiskie.udisks2: found device owning 
"/dev/disk/by-uuid/4E1AEA7B1AEA6007": 
"/org/freedesktop/UDisks2/block_devices/sde1"
DEBUG [2016-04-19 14:00:02,343] udiskie.mount: mounting 
/org/freedesktop/UDisks2/block_devices/sde1 with {'fstype': 'ntfs', 
'options': ['umask=0022']}
ERROR [2016-04-19 14:00:02,349] udiskie.mount: failed to mount 
/org/freedesktop/UDisks2/block_devices/sde1:
GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorizedCanObtain: Not 
authorized to perform operation
++ hostname
++ date +%Y-%m-%d:%H.%M
+ borg create --compression zlib,9 --stats '/media/faheem/My 
Passport/backup-Mail::orwell-2016-04-19:14.00' /home/faheem/Mail
Repository /media/faheem/My Passport/backup-Mail does not exist.

**Comment by coldfix** [comment]
Great! This output contains the actual problem: The authorization can't be obtained.

This is probably due to polkit not being configured to let none-active sessions mount. Take a look at the section on [Permissions](https://github.com/coldfix/udiskie/wiki/Permissions) in the wiki. In particular, I guess that adding the "XXX-other-seat" permissions will fix your problem. Let me know if that helps.

**Comment by fmitha** [comment]
Hi @coldfix ,

Ok, I'll take a look at the Wiki documentation and get back to you. Thanks.

**Comment by fmitha** [comment]
It doesn't seem to be working here. See https://unix.stackexchange.com/q/277606/4671

Suggestions for debugging appreciated. I still don't understand what makes a cron job special, though.

**Comment by coldfix** [comment]
Can you log the polkit activity as described [here](https://github.com/coldfix/udiskie/wiki/Debugging-a-problem#polkit), start following the system log before modifying the polkit config so you can observe when it reloads and if there is any error.

It is not cron jobs that are considered special but so-called *active* sessions, i.e. sessions that require *physical access* to the PC, by sitting in front of it and entering your password. Cronjobs, SSH sessions, systemd units and in general sessions that can be setup remotely are considered less secure and enjoy less privileges (but to be honest, they still allow full access to the system by modifying some config file such as `.bashrc` or `.profile`, etc and waiting for the user to log in - possibly, the distinction was introduced to avoid *accidental* execution of some tasks).

**Comment by coldfix** [comment]
Oh by the way, I didn't read your other post at first.

> Additionally, would it make sense to add a file such as that described in https://github.com/coldfix/udiskie/wiki/Permissions
to the Debian package? In any case, I'll file a bug against the Debian package about this.

Not sure. I think in doubt its probably better to leave it out. (Only few users will need it and there are some security implications..)

> I see the script using the non-existent group storage. Would using the group backup make sense?

You can call the group whatever you like:) The important thing is that it exists and that you are on it!

**Comment by fmitha** [comment]
> Can you log the polkit activity as described here, start following the system log before modifying the polkit config so you can observe when it reloads and if there is any error.

I was reliably informed that the pkit version in jessie doesn't do JS syntax; it's too old Can you offer a version of that debugging code that might work with the version in jessie?

**Comment by coldfix** [comment]
Oh.. in that case use the config as [described below](https://github.com/coldfix/udiskie/wiki/Permissions#policykit) but insert the correct action names.

**Comment by fmitha** [comment]
Ok, I'm now trying 
```
[udiskie]
Identity=unix-group:backup
Action=org.freedesktop.udisks2.filesystem-mount-other-seat;org.freedesktop.udisks2.filesystem-unmount-others;org.freedesktop.udisks2.encrypted-unlock-other-se\
at;org.freedesktop.udisks2.eject-media-other-seat;org.freedesktop.udisks2.power-off-drive-other-seat
ResultAny=yes
```
However, still no luck. Can I put Actions on multiple lines?

Also, what would the "old" version of the debugging stanza in https://github.com/coldfix/udiskie/wiki/Debugging-a-problem#polkit look like, and
what file location should I put it in?

Currently

    journalctl -n 20 -f -u polkit.service

shows bugger all.

As regards your earlier comments about the Debian package, even such a rule was not included in the package by default, I think it could reasonably be included in a README.Debian, so users would not have to through all these gyrations.

**Comment by coldfix** [comment]
> Can I put Actions on multiple lines?

You can do it like another user suggested [here](https://github.com/coldfix/udiskie/wiki/Ubuntu-Debian-installation-guide).

Just to make sure, you are in group `backup`, right? Use the `groups` command to verify. (I've seen lots of similar mistakes being made, so don't take this as an offense)

Also, is the config item with the actions really split in two lines in your config file? If so, I'm not sure if that works. Better put everything in one line.

> Also, what would the "old" version of the debugging stanza in https://github.com/coldfix/udiskie/wiki/Debugging-a-problem#polkit look like, and
what file location should I put it in?

Personally, I don't know much about old PolicyKit, but I'd guess that injecting a similar hook to monitor permission requests is not as easy if monitoring is not supported out of the box. Try following the `udisks2` log instead:

```
journalctl -fu udisks2
```

> Currently
> ```
> journalctl -n 20 -f -u polkit.service
> ```
> shows bugger all.

?

**Comment by fmitha** [comment]
Hi ThomasG,

Thanks for your help with this. It's been quite frustrating.

Ok, I tried the following, with a wildcard, as per the [link](https://github.com/coldfix/udiskie/wiki/Ubuntu-Debian-installation-guide) you posted. This worked.
I put the following in: `/etc/polkit-1/localauthority/50-local.d# less 10-udiskie.pkla`:

```
[udisks]
Identity=unix-group:plugdev
Action=org.freedesktop.udisks.*
ResultAny=yes
[udisks2]
Identity=unix-group:plugdev
Action=org.freedesktop.udisks2.*
ResultAny=yes
```
In the interests of my sanity, this seemed preferable to trying to figure out which of the many possible actions, apparently listed in https://udisks.freedesktop.org/docs/latest/udisks-polkit-actions.html, would work.

Note: `journalctl -fu udisks2` shows nothing on error. It only produces output on success, as far as I can see. So it is useless as a debugging tool.

And I'm in both the `plugdev` and `backup` groups. But I decided to use `plugdev`, since I was already in it, and `backup` isn't really designed to be used this way.

By
> shows bugger all.

I meant it shows nothing. British slang.

I'm now getting:

```
+ CLEVEL=zlib,9
+ udiskie-mount -o umask=0022 /dev/disk/by-uuid/4E1AEA7B1AEA6007 --verbose
DEBUG [2016-04-21 14:29:01,628] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/faheem/.config/udiskie/config.yml'
DEBUG [2016-04-21 14:29:01,630] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/faheem/.config/udiskie/config.json'
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
DEBUG [2016-04-21 14:29:01,849] udiskie.config: IgnoreDevice(match={'is_block': False}, value=True) created
DEBUG [2016-04-21 14:29:01,849] udiskie.config: IgnoreDevice(match={'is_external': False}, value=True) created
DEBUG [2016-04-21 14:29:01,849] udiskie.config: IgnoreDevice(match={'is_ignored': True}, value=True) created
DEBUG [2016-04-21 14:29:01,850] udiskie.udisks2: found device owning "/dev/disk/by-uuid/4E1AEA7B1AEA6007": "/org/freedesktop/UDisks2/block_devices/sde1"
DEBUG [2016-04-21 14:29:01,851] udiskie.mount: mounting /org/freedesktop/UDisks2/block_devices/sde1 with {'fstype': 'ntfs', 'options': ['umask=0022']}
DEBUG [2016-04-21 14:29:03,340] udiskie.udisks2: +++ device_mounted: /org/freedesktop/UDisks2/block_devices/sde1
DEBUG [2016-04-21 14:29:03,340] udiskie.udisks2: +++ device_changed: /org/freedesktop/UDisks2/block_devices/sde1
INFO [2016-04-21 14:29:03,340] udiskie.mount: mounted /org/freedesktop/UDisks2/block_devices/sde1 on /media/faheem/My Passport
+ udiskie-umount /dev/disk/by-uuid/4E1AEA7B1AEA6007
unmounted /org/freedesktop/UDisks2/block_devices/sde1
```

So, what's with the 
```    
Unable to init server: Could not connect: Connection refused
```
message? I guess this brings us back to this issue.

**Comment by coldfix** [comment]
> It's been quite frustrating.

I know the feeling...

> Ok, I tried the following, with a wildcard, as per the link you posted. This worked.

Great that it worked. However, it might not be the best idea to allow every udisks action.

I just tried running udiskie inside a cronjob on my system (why didn't I do this sooner?) and determined that the required action is indeed `org.freedesktop.udisks2.filesystem-mount-other-seat` when nobody is logged in and `org.freedesktop.udisks2.filesystem-mount` when somebody is logged into the system in an active session. So both actions must be enabled.  However, unless you made a syntax error in the config file (what about that backlash and split line?) something is probably different in your case.

> I meant it shows nothing. British slang.

Good to know:)

>  So, what's with the
> ```
> Unable to init server: Could not connect: Connection refused
> ```
> message? I guess this brings us back to this issue.

I wouldn't worry about this too much. This is just a warning from udiskie trying to determine whether an X server is running so it can prompt for a password using a graphical password dialog in case it has to mount a crypto device. I admit that this should be done a little smarter and probably not happen in cases where no password is required, but that's no priority for me now (have to finish my master thesis first:P). But I'll keep this issue open until I have time to fix.

Another thing you mentioned, the return code does not signify whether the mount-operation succeeded. IMO, this is a serious bug that I can confirm, I opened issue #110 for this, so I can get to fix this in about 2 or 3 weeks.

Best regards, and thanks,
it's always appreciated when you report problems or have suggestions,
Thomas

**Comment by fmitha** [comment]
Hi Thomas;

> Great that it worked. However, it might not be the best idea to allow every udisks action.

Possibly true.

> I just tried running udiskie inside a cronjob on my system (why didn't I do this sooner?) and determined that the required action is indeed org.freedesktop.udisks2.filesystem-mount-other-seat when nobody is logged in and org.freedesktop.udisks2.filesystem-mount when somebody is logged into the system in an active session. So both actions must be enabled. However, unless you made a syntax error in the config file (what about that backlash and split line?) something is probably different in your case.

Does umount also work? I'll try it with just these two.

> I wouldn't worry about this too much. This is just a warning from udiskie trying to determine whether an X server is running so it can prompt for a password using a graphical password dialog in case it has to mount a crypto device. I admit that this should be done a little smarter and probably not happen in cases where no password is required, but that's no priority for me now (have to finish my master thesis first:P). But I'll keep this issue open until I have time to fix.

Ok. Is this actually the same thing as was reported as issue 102?

> Another thing you mentioned, the return code does not signify whether the mount-operation succeeded. IMO, this is a serious bug that I can confirm, I opened issue #110 for this, so I can get to fix this in about 2 or 3 weeks.

Excellent.

> it's always appreciated when you report problems or have suggestions,

It's great you feel this way. Not everyone does.

Regards, Faheem

**Comment by fmitha** [comment]
Update:
I changed `/etc/polkit-1/localauthority/50-local.d/10-udiskie.pkla` to
```
[udisks2]
Identity=unix-user:faheem
Action=org.freedesktop.udisks2.filesystem-mount-other-seat;org.freedesktop.udisks2.filesystem-mount
ResultAny=yes
```
The mounting and unmounting in the cron job is still working. I still feel that there should be something about this in the Debian packages to warn unwary users before they trip over this minefield. Doing mounting/unmounting inside a cron job is hardly an unusual thing to do, anyway.

I do get the following logs:
```
Apr 22 05:40:57 orwell polkitd[4442]: Entering main event loop
Apr 22 05:40:57 orwell polkitd[4442]: Connected to the system bus
Apr 22 05:40:57 orwell polkitd[4442]: Registering null backend at priority -10
Apr 22 05:40:57 orwell polkitd[4442]: started daemon version 0.105 using authority implementation `local' version `0.105'
Apr 22 05:40:57 orwell polkitd[4442]: Using authority class PolkitBackendLocalAuthority
Apr 22 05:40:57 orwell polkitd[4442]: Acquired the name org.freedesktop.PolicyKit1
Apr 22 05:40:57 orwell polkitd[4442]: ** (polkitd:4442): WARNING **: skipping unknown tag <i> at line 341
```
I think the `skipping unknown tag <i> at line 341` bit is unrelated to udiskie, though.

**Comment by jasonwryan** [comment]
> Doing mounting/unmounting inside a cron job is hardly an unusual thing to do, anyway.

Well, I would characterise it as unusual; there are better ways to do it that do not require these sorts of workarounds. I use a --user service file and that is a far easier, and more resilient, approach. Cron jobs are a pretty kludgy option by comparison.

**Comment by fmitha** [comment]
@jasonwryan 
Ok. Well, cron has been around for a long time. Maybe there are better ways to do things now.
Would you care to share your `--user` service file? I'm always willing to learn.

Regards, Faheem Mitha

**Comment by jasonwryan** [comment]
@fmitha 

Sure: there is nothing to it:
```
[Unit]
Description=Automounting Daemon

[Service]
ExecStart=/usr/bin/udiskie -qN

[Install]
WantedBy=default.target
```

**Comment by fmitha** [comment]
Ok. And where would this file live?

**Comment by jasonwryan** [comment]
See: https://wiki.archlinux.org/index.php/Systemd/User for how to set up user services...

**Comment by fmitha** [comment]
Hmm. It's not clear to me how this is a substitute for a cron job. The service file would just be a way to start and stop udiskie, right?

**Comment by jasonwryan** [comment]
Yes. If you want a scheduler, use a timer file for the service.

This is, however, somewhat outside the remit of this issue, or even this repo...

**Comment by fmitha** [comment]
> Yes. If you want a scheduler, use a timer file for the service.

Ok. Thank you.
