### ISSUE TITLE
Patch for Debian package documenting possible policykit issues

### ISSUE THREAD

**Issue by fmitha** [coldfix/udiskie#111]
Hi,

I just heard back from the udiskie Debian maintainer, Gianfranco Costamagna
(see https://bugs.debian.org/822209).

He said

> Hi, can you please provide a patch for this?
I can also install a policykit file if needed, just please send a patch

Though this is not strictly an upstream issue, I decided to open an issue to keep track of the discussion. I hope that is Ok.

Do you have any opinions what kind of addition to make to the Debian package?

Option 1: Warn users that they may have permission problems under certain circumstances
in README.Debian. The `cron` issue you ran into is one such. There may be others. 
It would also be reasonable to suggest an example patch, I think.

Option 2: Provide a policykit patch in addition to the README, Debian. But that might be problematic; different people have different ideas what is reasonable.

Here is a first attempt at a README.Debian. Currently one does not exist.

############################################################

Note that by default not all udiskie actions may be allowed. You may see an error like:

    GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorizedCanObtain: Not
authorized to perform operation

That error means you need to give udiskie addition permissions to perform whatever actions are necessary. These permissions are governed by policykit (package `policykit-1` in Debian), 

Here is an example. If you run `udiskie-mount` and/or `udiskie-umount` inside a user cron job, you will need to grant your user additional permissions for the policykit actions as follows:

1) `org.freedesktop.udisks2.filesystem-mount-other-seat` for when nobody is logged in and 

2) `org.freedesktop.udisks2.filesystem-mount` when somebody is logged into the system in an active session.

To grant these permissions, you can (for example) create a file called `/etc/polkit-1/localauthority/50-local.d/10-udiskie.pkla` containing the following:
```
[udisks2]
Identity=unix-group:plugdev
Action=org.freedesktop.udisks2.filesystem-mount-other-seat;org.freedesktop.udisks2.filesystem-mount
ResultAny=yes

```
This gives the necessary permissions to all users in the `plugdev` group. If you wish to only give permissions to a single user, you can replace the first line with
```
Identity=unix-group:plugdev
```
Note additionally that the policykit version in Debian (for jessie and later) is 105. The Javascript syntax you will see for Policykit is for versions 106 and later. The `*.pkla` suffix and the corresponding syntax is only used for policykit 105 and earlier.

**Comment by coldfix** [comment]
> Do you have any opinions what kind of addition to make to the Debian package?

Not really. I'm actually somewhat happy that I don't have to make these decisions:)
Improving the documentation as you suggest is in any case a good idea!

**Comment by fmitha** [comment]
On Mon, 25 Apr 2016, Thomas G. wrote:

>>      Do you have any opinions what kind of addition to make to the
>>      Debian package?

> Not really. I'm actually somewhat happy that I don't have to make these
> decisions:) Improving the documentation as you suggest is in any case a
> good idea!

Hi Thomas,

Ok. I just opened an issue for the patch because I thought you (or
possibly someone else) might have opinions. Feel free to close the issue
if you wish. Should I just send the patch direct to the Debian maintainer,
then?

                                                    Regards, Faheem Mitha

**Comment by yakir12** [comment]
Hi, 
I'm getting the following error on a Debian without any DE:
`failed to mount /org/freedesktop/UDisks2/block_devices/sdb1: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorized: Not authorized to perform operation`
Seemed relevant. The instruction with the `10-udiskie.pkla` file didn't work though (I did try installing `policykit-1`).
Appreciate any help!

**Comment by fmitha** [comment]
Hi Yakir,

On Wed, 4 May 2016, Yakir Luc Gagnon wrote:

> Hi,

> I'm getting the following error on a Debian without any DE: failed to 
> mount /org/freedesktop/UDisks2/block_devices/sdb1: 
> GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorized: Not authorized 
> to perform operation Seemed relevant. The instruction with the 
> 10-udiskie.pkla file didn't work though (I did try installing 
> policykit-1). Appreciate any help!

The patch I posted should work. It works here. What version of Debian are 
you running? I don't think it depends on a DE, but I'm not 100% sure. 
Policykit seems like a bit of a black art.

Did you install

[udisks2]
Identity=unix-user:faheem
Action=org.freedesktop.udisks2.filesystem-mount-other-seat;org.freedesktop.udisks2.filesystem-mount
ResultAny=yes

as /etc/polkit-1/localauthority/50-local.d/10-udiskie.pkla?

The next step would be to run polkit in debug mode. By default polkit runs 
in debug mode, but has a no-debug flag.

You can change this in /lib/systemd/system/polkitd.service.

Remove --no-debug from

     ExecStart=/usr/lib/policykit-1/polkitd --no-debug

And you will need to restart with

     systemctl restart polkitd

You could also try the policykit mailing list. I posted there, and someone 
did reply, though he wasn't super helpful. If you do write to the ml, 
please cc me. Thanks.

                                                      Regards, Faheem Mitha

**Comment by yakir12** [comment]
Hi Faheem!
Thanks for the reply. Its a Debian testing (stretch), and I used `Identity=unix-group:plugdev` in the `/etc/polkit-1/localauthority/50-local.d/10-udiskie.pkla` file (instead of your `Identity=unix-user:faheem`). I am a member in the `plugdev` group.

After removing the `--no-debug` flag I got the following:
```bash
yakir@debian:~$ systemctl restart polkitd
** (process:2633): WARNING **: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.NotSupported: Operation not supported
Error registering authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.NotSupported: Operation not supported (polkit-error-quark, 2)
Failed to restart polkitd.service: Access denied
See system logs and 'systemctl status polkitd.service' for details.
yakir@debian:~$ sudo systemctl restart polkitd
Warning: polkitd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
```
Not sure where to take it from there?

**Comment by fmitha** [comment]
On Wed, 4 May 2016, Yakir Luc Gagnon wrote:

> Hi Faheem!

> Thanks for the reply. Its a Debian testing (stretch), and I used
> Identity=unix-group:plugdev in the
> /etc/polkit-1/localauthority/50-local.d/10-udiskie.pkla file (instead of
> your Identity=unix-user:faheem). I am a member in the plugdev group.

Ok. I think stretch should work.

> After removing the --no-debug flag I got the following:

> yakir@debian:~$ systemctl restart polkitd
> ** (process:2633): WARNING **: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.NotSupported: Operation not suppo
> rted
> Error registering authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.NotSupported: Operation not supported (polkit-error-quark, 2)
> Failed to restart polkitd.service: Access denied
> See system logs and 'systemctl status polkitd.service' for details.
> yakir@debian:~$ sudo systemctl restart polkitd
> Warning: polkitd.service changed on disk. Run 'systemctl daemon-reload' to reload units.

> Not sure where to take it from there?

First, rerun 'systemctl daemon-reload`. That warning was preusmaboly
because you changed the polkitd.service file.  Then try again.

It says see system logs and 'systemctl status polkitd.service'. See if
either of those provide further information. Generally
`/var/log/syslog`, and `/var/log/messages` are the first places to
look. Or you could grep `/var/log` for polkit.

Regards, Faheem Mitha

**Comment by yakir12** [comment]
Thanks again Faheem,
Strange, the [logs](http://pastebin.com/y3zwivbF) don't show any failure. 
I still can't mount with `udiskie` but I can successfully mount "manually":
```
...@...:~$ udiskie-mount -a
failed to mount /org/freedesktop/UDisks2/block_devices/sdb1: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorized: Not authorized to perform operation
...@...:~$ sudo mount /dev/sdb1 /tmp/
...@...:~$ 
```
All of this is after a restart. Thing is, I had `udiskie` work perfectly two weeks ago. I can only assume some upgrade broke something.

**Comment by fmitha** [comment]
Hi Yakir,

On Thu, 5 May 2016, Yakir Luc Gagnon wrote:


> Thanks again Faheem,
> Strange, the logs don't show any failure.
> I still can't mount with udiskie but I can successfully mount "manually":

> ...@...:~$ udiskie-mount -a
> failed to mount /org/freedesktop/UDisks2/block_devices/sdb1: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorized: Not authorized to perform operat
> ion

Oh, this wasn't clear from your earlier message - you failed to mention 
what command you were typing, and I assumed (wrongly) that you were trying 
to run udiskie as a cron job. From the command line no additional 
permissions are necessary. The script I mentioned in this issue was for 
mounting via cron. So something else is going on with your setup. Maybe 
file a different issue?

Thomas, what do you think?

> ...@...:~$ sudo mount /dev/sdb1 /tmp/
> ...@...:~$

That doesn't use udiskie. That's a completely separate matter.

> All of this is after a restart. Thing is, I had udiskie work perfectly 
> two weeks ago. I can only assume some upgrade broke something.

That seems unlikely. What version of udiskie are you running?

                                                    Regards, Faheem Mitha

**Comment by yakir12** [comment]
`udiskie 1.4.9`
Shall I open a new issue then?

**Comment by fmitha** [comment]
On Thu, 5 May 2016, Yakir Luc Gagnon wrote:

> 
> udiskie 1.4.9
> Shall I open a new issue then?

Yes, I think so. Make sure to include all details.
