### ISSUE TITLE
Excessive notifications with docker

### ISSUE THREAD

**Issue by mika-fischer** [coldfix/udiskie#113]
When using docker, a lot of stuff is mounted and unmounted under the hood and `udiskie --tray` basically fills my entire screen with notifications.

Is there a way udiskie could ignore those or any other way around displaying them?

**Comment by coldfix** [comment]
Hey, sorry for the late reply.

I've uploaded a patch that will hopefully fix the problem - at least on my system no more notifications are shown. You can check it out on the branch `fix-docker` or wait for a release in the next week or so.

**Comment by mika-fischer** [comment]
Yes, that fixes it, thanks!

**Comment by coldfix** [comment]
Fixed by 5cb7f5da816076aca62b0f22128b0196f82a277a
