### ISSUE TITLE
GDBus.Error

### ISSUE THREAD

**Issue by yakir12** [coldfix/udiskie#115]
Hi,
I can't mount with `udiskie 1.4.9` on a headless Debian testing (stretch) but I can successfully mount "manually":
```
...@...:~$ udiskie-mount -a
failed to mount /org/freedesktop/UDisks2/block_devices/sdb1: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorized: Not authorized to perform operation
...@...:~$ sudo mount /dev/sdb1 /tmp/
...@...:~$ 
```
See more details in  #111 
Appreciate any help!

**Comment by coldfix** [comment]
Hey,

looks like you are missing some permissions, see here:

https://github.com/coldfix/udiskie/wiki/Permissions

Look at which version of policykit you are running
- version 2 -> use the instructions at the top
- version 1 -> use the instructions at the bottom

You need these in particular:

```
    org.freedesktop.udisks2.filesystem-mount
    org.freedesktop.udisks2.encrypted-unlock
    org.freedesktop.udisks2.eject-media
    org.freedesktop.udisks2.power-off-drive
```

but won't hurt much to allow all, that's described there.

Sorry, I didn't read through the other thread carefully. Just get back to me, if this doesn't work.

**Comment by yakir12** [comment]
Do I even need to install `polkit-kde-1`? I didn't have a `/etc/polkit-1/rules.d/` directory (to put the `50-udiskie.rules` file in) neither before nor after installing `polkit-kde-1`, so I made that directory but that didn't help. Is it the `mate-polkit` package and not the `polkit-kde-1` package that I need? How do I find out which version of policykit I'm running?

**Comment by coldfix** [comment]
Try installing `policykit-1` if it wasn't sucked in by udisks automatically - and use the second suggested configuration. Include all listed permissions for udisks2 (could be that headless requires the XXX-other-seat permissions).

If this doesn't work, please send the output of `udisksctl info -b /dev/sdb1`.

**Comment by coldfix** [comment]
@yakir12 did this fix your problem?

**Comment by yakir12** [comment]
So sorry for being slow. On a spontaneous vacation. In check this in about
a week!
Den 10 maj 2016 23:23 skrev "Thomas G." <notifications@github.com>:

**Comment by yakir12** [comment]
I'm baaaack..
It didn't work. This is the output of `udisksctl info -b /dev/sdb1`:
```
/org/freedesktop/UDisks2/block_devices/sdb1:
  org.freedesktop.UDisks2.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/sdb1
    DeviceNumber:               2065
    Drive:                      '/org/freedesktop/UDisks2/drives/SAMSUNG_HM500JI_152D203380B6'
    HintAuto:                   true
    HintIconName:               
    HintIgnore:                 false
    HintName:                   
    HintPartitionable:          true
    HintSymbolicIconName:       
    HintSystem:                 false
    Id:                         by-id-usb-SAMSUNG_HM500JI_152D203380B6-0:0-part1
    IdLabel:                    orangeYG
    IdType:                     ntfs
    IdUUID:                     0BABC27B1B4987D9
    IdUsage:                    filesystem
    IdVersion:                  
    MDRaid:                     '/'
    MDRaidMember:               '/'
    PreferredDevice:            /dev/sdb1
    ReadOnly:                   false
    Size:                       500106788864
    Symlinks:                   /dev/disk/by-id/usb-SAMSUNG_HM500JI_152D203380B6-0:0-part1
                                /dev/disk/by-label/orangeYG
                                /dev/disk/by-path/pci-0000:00:1d.7-usb-0:1:1.0-scsi-0:0:0:0-part1
                                /dev/disk/by-uuid/0BABC27B1B4987D9
  org.freedesktop.UDisks2.Filesystem:
    MountPoints:        
  org.freedesktop.UDisks2.Partition:
    Flags:              0
    IsContained:        false
    IsContainer:        false
    Name:               
    Number:             1
    Offset:             1048576
    Size:               500106788864
    Table:              '/org/freedesktop/UDisks2/block_devices/sdb'
    Type:               0x07
    UUID:               00080b60-01
```

**Comment by coldfix** [comment]
```
groups

cat /etc/polkit-1/localauthority/50-local.d/10-udisks.pkla

udiskie-mount -v /dev/sdb1
```

Are there any other policykit rules that may deny the authorization?

**Comment by yakir12** [comment]
omg, sorry for being so slow!!!
```
$ groups
yakir cdrom floppy sudo audio dip video plugdev netdev lpadmin scanner bluetooth storage
$ cat /etc/polkit-1/localauthority/50-local.d/10-udisks.pkla
cat: /etc/polkit-1/localauthority/50-local.d/10-udisks.pkla: No such file or directory
$ udiskie-mount -v /dev/sdb1
DEBUG [2016-06-13 10:18:46,203] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/yakir/.config/udiskie/config.yml'
DEBUG [2016-06-13 10:18:46,208] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/yakir/.config/udiskie/config.json'
DEBUG [2016-06-13 10:18:46,279] udiskie.config: IgnoreDevice(match={'symlinks': '/dev/mapper/docker-*'}, value=True) created
DEBUG [2016-06-13 10:18:46,280] udiskie.config: IgnoreDevice(match={'symlinks': '/dev/disk/by-id/dm-name-docker-*'}, value=True) created
DEBUG [2016-06-13 10:18:46,280] udiskie.config: IgnoreDevice(match={'is_block': False}, value=True) created
DEBUG [2016-06-13 10:18:46,280] udiskie.config: IgnoreDevice(match={'is_external': False}, value=True) created
DEBUG [2016-06-13 10:18:46,281] udiskie.config: IgnoreDevice(match={'is_ignored': True}, value=True) created
DEBUG [2016-06-13 10:18:46,282] udiskie.udisks2: found device owning "/dev/sdb1": "/org/freedesktop/UDisks2/block_devices/sdb1"
DEBUG [2016-06-13 10:18:46,284] udiskie.mount: mounting /org/freedesktop/UDisks2/block_devices/sdb1 with {'options': None, 'fstype': 'ntfs'}
ERROR [2016-06-13 10:18:46,292] udiskie.mount: failed to mount /org/freedesktop/UDisks2/block_devices/sdb1: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorized: Not authorized to perform operation
```
we can `tmate` if you like.

**Comment by coldfix** [comment]
```
$ cat /etc/polkit-1/localauthority/50-local.d/10-udisks.pkla
cat: /etc/polkit-1/localauthority/50-local.d/10-udisks.pkla: No such file or directory
```

Didn't you create the policykit rules?

> we can tmate if you like.

Good idea. When do you have time?

**Comment by tvidal-34** [comment]
Dear coldfix,

I have exactly the same problem.
Debian 8.5 with policykit.

`kiosk@ihm:~$ sudo cat /etc/polkit-1/localauthority/50-local.d/10-automount.pkla
[udisks1]
Identity=unix-user:kiosk
Action=org.freedesktop.udisks.filesystem-mount;org.freedesktop.udisks.luks-unlock;org.freedesktop.udisks.drive-eject;org.freedesktop.udisks.drive-detach
ResultAny=yes

[udisks2]
Identity=unix-user:kiosk
Action=org.freedesktop.udisks2.filesystem-mount,org.freedesktop.udisks2.encrypted-unlock,org.freedesktop.udisks2.eject-media,org.freedesktop.udisks2.power-off-drive
ResultAny=yes

[udisks2-other-seat]
Identity=unix-user:kiosk
Action=org.freedesktop.udisks2.filesystem-mount-other-seat,org.freedesktop.udisks2.filesystem-unmount-others,org.freedesktop.udisks2.encrypted-unlock-other-seat,org.freedesktop.udisks2.eject-media-other-seat,org.freedesktop.udisks2.power-off-drive-other-seat
ResultAny=yes
`
and in the syslog when I plug a USB key :
`Jul 29 09:49:01 ihm udiskie[750]: ERROR [2016-07-29 09:49:01,325] udiskie.mount: failed to mount /org/freedesktop/UDisks2/block_devices/sdb1: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorizedCanObtain: Not authorized to perform operation`

Many many thanks for your help.

All the best

Thomas

**Comment by tvidal-34** [comment]
I change the policy to :

```
[udisks1]
Identity=unix-user:*
Action=org.freedesktop.udisks*
ResultAny=yes
[udisks2]
Identity=unix-user:*
Action=org.freedesktop.udisks*
ResultAny=yes
[udisks2-other-seat]
Identity=unix-user:*
Action=org.freedesktop.udisks*
ResultAny=yes
```
And now it's working...  but I don't understand the reason as for sure my kiosk user was in plugdev group....
And this is not really cool to allow everything to everyone !

If someone find a better solution and why we got the problem... you're welcome.

Cheers

**Comment by coldfix** [comment]
Hey,

thanks for your message.

Can you try gradually going back to the suggested configuration to see what exactly was required? I'd be surprised if this is about the user, not about the kind of permission.

i.e. first try:

```
[udisks1]
Identity=unix-user:*
Action=org.freedesktop.udisks*
ResultAny=yes
[udisks2]
Identity=unix-user:*
Action=org.freedesktop.udisks*
ResultAny=yes
[udisks2-other-seat]
Identity=unix-user:kiosk
Action=org.freedesktop.udisks1*
ResultAny=yes

[udisks2]
Identity=unix-user:kiosk
Action=org.freedesktop.udisks2*
ResultAny=yes
[udisks2-other-seat]
Identity=unix-user:kiosk
Action=org.freedesktop.udisks2*
ResultAny=yes
```

and then successively remove permissions.

**Comment by tvidal-34** [comment]
Hi, yes I will do it. Be back in few hours with the output.

**Comment by tvidal-34** [comment]
Do I just need to do a "systemctl restart polkitd.service" between the test ? or is it better to reboot the computer ?

**Comment by coldfix** [comment]
t.b.h. I don't know whether you need that with policykit. With polkit (i.e. policykit 2), there is no need (but that uses different configuration files).

**Comment by tvidal-34** [comment]
ok, so :
When changing 
Identity=unix-user:*    to    Identity=unix-user:kiosk
Evertyhting is still working

But when adding all org files like :
```
[udisks1]
Identity=unix-user:kiosk
Action=org.freedesktop.udisks.filesystem-mount;org.freedesktop.udisks.luks-unlock;org.freedesktop.udisks.drive-eject;org.freedesktop.udisks.drive-detach
ResultAny=yes
[udisks2]
Identity=unix-user:kiosk
Action=org.freedesktop.udisks2.filesystem-mount,org.freedesktop.udisks2.encrypted-unlock,org.freedesktop.udisks2.eject-media,org.freedesktop.udisks2.power-off-drive
ResultAny=yes
[udisks2-other-seat]
Identity=unix-user:kiosk
Action=org.freedesktop.udisks2.filesystem-mount-other-seat,org.freedesktop.udisks2.filesystem-unmount-others,org.freedesktop.udisks2.encrypted-unlock-other-seat,org.freedesktop.udisks2.eject-media-other-seat,org.freedesktop.udisks2.power-off-drive-other-seat
ResultAny=yes
```
I have the problem.

So I have to check all these org.freedesktop.* to find what is going wrong ....

Thomas

**Comment by coldfix** [comment]
Great, now we have some clue.

> So I have to check all these org.freedesktop.* to find what is going wrong ....

Not really.

First, your error message indicates, the problem is UDisks2.

Second, only mounting (that's the operation you are trying to perform, right?) is relevant.

So the only relevant actions should be:

- `org.freedesktop.udisks2.filesystem-mount`
- `org.freedesktop.udisks2.filesystem-mount-system`
- `org.freedesktop.udisks2.filesystem-mount-other-seat`
- `org.freedesktop.udisks2.filesystem-mount-fstab`

Apparently, authorization is denied when using `org.freedesktop.udisks2.filesystem-mount` and `org.freedesktop.udisks2.filesystem-mount-other-seat`. So we are left with one of:

- `org.freedesktop.udisks2.filesystem-mount-system`
- `org.freedesktop.udisks2.filesystem-mount-fstab`

Try adding them individually and see if the problems goes away. For @yakir12, the device was recognized as external, so the first option should not be his problem.

**Comment by coldfix** [comment]
Oh, I just looked more closely at the config format. There seems to be an error in the example for udisks2.... The actions should be separated using semi-colons `;` rather than commas `,`. Try this first.

**Comment by tvidal-34** [comment]
Dear Thomas,

It (&I)  was so stupid ! You're right ! "," instead of ";" for udisks2 !!! The bad thing is that there was nothing in the log about this error.
Anyway, everything is working fine now !!! Many many thanks !!!

Cheers

Thomas

**Comment by coldfix** [comment]
Great! It was my fault writing commas into the example by accident.

 @yakir12: Feel free to reopen if your problem remains.
