### ISSUE TITLE
error in notifying-subsystem

### ISSUE THREAD

**Issue by cherti** [coldfix/udiskie#117]
## Problem description

Notifications are not working, producing an exception instead.
Core-functionality is not affected.

### Steps to reproduce:
1. start `udiskie -F`
2. attach harddrive (tested with USB3-HDD with NTFS on it)
3. get stacktrace below, no notification (but your device still gets mounted properly, see last line of the stacktrace that actually doesn't belong to the stacktrace)

Adding `-v` doesn't seem to provide further output related to this problem.

### Stacktrace
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/udiskie/dbus.py", line 295, in __call__
    return self._handler(object_path, *unpack_variant(parameters))
  File "/usr/lib/python3.5/site-packages/udiskie/udisks2.py", line 817, in _job_completed
    self.trigger(event_name, device)
  File "/usr/lib/python3.5/site-packages/udiskie/udisks2.py", line 649, in trigger
    super(Daemon, self).trigger(event, device, *args)
  File "/usr/lib/python3.5/site-packages/udiskie/common.py", line 72, in trigger
    handler(*args)
  File "/usr/lib/python3.5/site-packages/udiskie/notify.py", line 73, in device_mounted
    self._mounter._browser and browse_action)
  File "/usr/lib/python3.5/site-packages/udiskie/notify.py", line 221, in _show_notification
    if self._action_enabled(event, action[0]):
TypeError: 'NoneType' object is not subscriptable
mounted /org/freedesktop/UDisks2/block_devices/sdf1 on /media/myharddisk
```

## Problem diagnosis

The exception is thrown [here](https://github.com/coldfix/udiskie/blob/master/udiskie/notify.py#L221) when accessing the first element of the first element of the actions-list, which happens to be the browser-field, which in turn is what is returned by [this function](https://github.com/coldfix/udiskie/blob/master/udiskie/prompt.py#L193), which is either a function object or `None`.

`None` is not subscriptable and therefore trigger the TypeError.

## Possible fixes

Possible fixes for this include
1. checking for `None` before accessing `action`'s first element right at the point of raisement.
2. adding a general check if the object is subscriptable.
3. adjusting [this function's](https://github.com/coldfix/udiskie/blob/master/udiskie/prompt.py#L193) returnvalue to always be subscriptable.

I'd say going for 1 or 2 (to avoid this type of error generally for the future) is the best choice here. What's upstream's opinion on this matter?

**Comment by coldfix** [comment]
Hey, thanks! You're right, there is a None-check clearly missing here.
