### ISSUE TITLE
Notification-Error with systemd --user

### ISSUE THREAD

**Issue by cherti** [coldfix/udiskie#118]
When using udiskie with notifications (`-n`) on the commandline, everything is fine, notifications show up when plugging a device. When the same udiskie-command is used with a systemd-user-servicefile, I find the following in the log:

`Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files`

The corresponding servicefile is (same symptoms if I entirely omit the `Environement=`)
```
# /home/cherti/.config/systemd/user/udiskie.service
[Unit]
Description=udiskie automounter
After=display-manager.service

[Service]
ExecStart=/usr/bin/udiskie -Pantv
Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus XDG_RUNTIME_DIR=/run/user/1000
Restart=on-failure

[Install]
WantedBy=default.target
```

`busctl --user | grep Notifications` returns

```
org.freedesktop.Notifications                              1090 awesome         cherti            :1.15733      session-c1.scope          c1         - 
```
So the notification daemon is there (obviously, as everything works fine from within a terminal).

Any ideas where to look for the root of the problem? Any further info that might help solving this?

**Comment by coldfix** [comment]
Hey, thanks for the report.

I can't reproduce the issue on my system. Does this happen if you start the unit while your window manager is already running, or only on autostart?

If only on autostart, my guess is the following: awesome has its own builtin notification daemon that can not be started automatically via dbus (I think), but is started when awesome starts up. So, you should make sure to start udiskie only when awesome is already running. Other option: install a dedicated notification daemon (I prefer `xfce4-notifyd`) and put something like this in your `rc.lua` to use it consistently:

```lua
-- make sure to always use the installed notification daemon rather than the builtin:
local _dbus = dbus; dbus = nil
local naughty = require("naughty")
dbus = _dbus
```

If you have a separate notification daemon installed: Does your `display-manager` unit make sure an X session is already running?

Do you get another error when running the unit without `-n`?

**Comment by cherti** [comment]
not related to a missing dbus-link, also happened when restarted from awesome (where the notification-daemon is present).

However, I don't know what I changed, but the issue is gone now. Unfortunately I cannot reproduce that issue anymore. Probably a misconfiguration on my part, therefore I'll close this.
