### ISSUE TITLE
NoneType error during launch

### ISSUE THREAD

**Issue by mokrinsky** [coldfix/udiskie#123]
I've got this error during launch of udiskie. I'm using 1.4.12 on gentoo with custom ebuild (the one in portage is older than Earth).

```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/udiskie/async_.py", line 293, in _interact
    value = func(*args)
  File "/usr/lib64/python3.4/site-packages/udiskie/mount.py", line 523, in add_all
    success = all(results)
TypeError: 'NoneType' object is not iterable
```

The same error while using python2_7. Tried to read some code near these lines, but I'm not python guru, so it gave me nothing. The only one thing I managed to find is that error appears only if I have no udiskie-managed devices attached. Like if I plug in usb-drive and than will do start-restart-whatever, I will have no such error.

N.B. seems like everything works fine even with this error, but I cannot be sure.

**Comment by coldfix** [comment]
Hey,

thanks for your report. I've located the source for this error message and fixed the problem. There will be a release in a few days. This error should not have any consequences on the functionality.

Best,
Thomas
