### ISSUE TITLE
Immediate crash on launch

### ISSUE THREAD

**Issue by matoro** [coldfix/udiskie#125]
As of a few days ago it was working fine, but udiskie now crashes on launch with the following traceback:

```
Traceback (most recent call last):
  File "/usr/bin/udiskie", line 9, in <module>
    load_entry_point('udiskie==1.4.12', 'console_scripts', 'udiskie')()
  File "/usr/lib/python3.5/site-packages/udiskie/cli.py", line 240, in main
    return cls(argv).run()
  File "/usr/lib/python3.5/site-packages/udiskie/cli.py", line 209, in __init__
    options.update(config.program_options)
  File "/usr/lib/python3.5/site-packages/udiskie/config.py", line 260, in program_options
    return self._data.get('program_options', {}).copy()
AttributeError: 'NoneType' object has no attribute 'get'
```

System specs:
```Linux arch 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux```

Also, this doesn't really warrant its own issue, but is there a way to disable the GTK3 notifications while still keeping the notify-osd ones?

**Comment by coldfix** [comment]
Hey,

by looking at the code, I believe that this can only happen if your config file (`~/.config/udiskie/udiskie`) exists but is empty - or contains a scalar `null`. I might fix the first scenario in a future release. For now, make sure to delete the config file if it does not contain any valid settings.

As for your second question: What does this mean, do you get all notifications from two notification daemons double? (I have never had this happen before, and this should be the responsibility of libnotify etc).

**Comment by matoro** [comment]
Thanks!  I forgot I had run a touch on the config file -_-'

On the second question, on insertion, I get a notification from libnotify, AND a GTK3 prompt that appears asking me what I want to do (browse, cancel, OK).  I'm looking for a way to either disable that prompt or force it to use GTK2.  Much appreciated!!!
