### ISSUE TITLE
Double notifications

### ISSUE THREAD

**Issue by coldfix** [coldfix/udiskie#126]
@mtorromeo  wrote in #125 (**EDIT: this was @matoro**)

> on insertion, I get a notification from libnotify, AND a GTK3 prompt that appears asking me what I want to do (browse, cancel, OK). I'm looking for a way to either disable that prompt or force it to use GTK2. Much appreciated!!!

Hey, I installed `notify-osd` and found out that the prompts you experienced are generated by `notify-osd` for notification actions. Personally, I recommend to switch to `xfce4-notifyd` where the actions are integrated into the notification bubbles (also, the notifications are IMO nicer and appear without delay). If you like to stay with `notify-osd`, you have two options:

Either you try to find whether *notify-osd* can be configured to ignore actions (I didn't find anything on this after a quick google search) - or you disable notification actions in the udiskie config. In this case add to your config file the following:

```yaml
notification_actions:
  device_mounted:   []
  device_added:     []
  job_failed:       []
```

**Comment by coldfix** [comment]
Sorry, this was @matoro's quote (auto-completion fail).

**Comment by matoro** [comment]
@coldfix Tried switching from notify-osd to xfce4-notifyd -- now all notification show up using GTK3, which is kind of the opposite of what I wanted.  It's pretty low-priority really, just that any GTK3 elements clash with my theme and are pretty much unconfigurable (damn you evince for being the only PDF viewer with touch support!)

According to the documentation udiskie can use GTK2 as a fallback should you not have GTK3 installed.  Wouldn't there be an easy way to force it to user GTK2 instead, perhaps adding a small option (--use-gtk2)?  Unfortunately I don't know python or I would do it myself.

**Comment by coldfix** [comment]
Oh, you're having issue with theme :D, I've given up on that one long ago:)

Regarding your question: there is no way to instruct xfce4-notifyd or notify-osd to use gtk2 from inside udiskie. This is entirely out of control of udiskie. You'd have to rewrite and rebuild those programs using gtk2;) Otherwise, you can go back to notify-osd and disable the actions, as suggested above.

A choice between gtk2/gtk3 inside udiskie is possible, but the only place where this is relevant are the password-entry dialogs for encrypted devices and only if you're using udiskie without the tray icon. So this isn't really anything I'd like to support using a command line switch (since I'd like to move away from gtk2 anyway, it lacks support for lots of useful stuff).

**Comment by matoro** [comment]
Thanks for the explanation!  I tried out the new config and it works perfectly.

**Comment by coldfix** [comment]
(Oh and by the way, [according to the wiki](https://wiki.archlinux.org/index.php/xfce), xfce should be using gtk2)

**Comment by matoro** [comment]
Yes, I was actually very confused by that.  I use xfce4-power-manager for power management and it uses GTK2 just fine.  Very odd that the notification daemon does not.

**Comment by coldfix** [comment]
Strange. What OS are you running? Here (archlinux), I have

```
ldd /usr/lib/xfce4/notifyd/xfce4-notifyd | grep gtk
	libgtk-x11-2.0.so.0 => /usr/lib/libgtk-x11-2.0.so.0 (0x00007fce00f90000)
```

looks like it's using gtk2 to me.

**Comment by matoro** [comment]
I'm on ```Linux arch 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux```

```libgtk-x11-2.0.so.0 => /usr/lib/libgtk-x11-2.0.so.0 (0x00007f6c1d52e000)```

Might be a deficiency in my theme somewhere.  All I know is it's got the same problem as all the gnome programs, which is that it completely ignores any theme changes I make.

I've always assumed this was a GTK2 vs GTK3 thing - i.e. the emacs package ignores theme, but emacs-gtk2 doesn't.  pavucontrol ignores it, but pavucontrol-gtk2 doesn't.  Etc. etc.

**Comment by coldfix** [comment]
Okay. I'm afraid I can't really help you here. For me theming has never really worked since I have KDE/GTK2/GTK3 applications all mixed up on my system. And then there is java. And webapplications.

Good luck,:)
Thomas
