### ISSUE TITLE
Can't disable notification.

### ISSUE THREAD

**Issue by manzerbredes** [coldfix/udiskie#128]
Hello, when I use udiskie 1.5.1 daemon, I can't disable notifycations (-N option and --no-notify does not work).

**Comment by coldfix** [comment]
Curious. Do you have several udiskie instances running, maybe there is still an udiskie daemon running in the background?

```
pkill udiskie
udiskie -N
```

**Comment by manzerbredes** [comment]
I don't know why, but it works now. In fact, I think I was running several instances of udiskie sorry.

**Comment by coldfix** [comment]
Okay, no problem.
