### ISSUE TITLE
--disable-notify does not appear to work as daemon

### ISSUE THREAD

**Issue by mindstormer12** [coldfix/udiskie#129]
`--disable-notify` as an option does not appear to work, at least in the following service file: 
    [Unit]
    Description=Automounting Daemon

    [Service]
    ExecStart=/usr/bin/udiskie --use-udisks2 --quiet --smart-tray --disable-notify --no-password-cache

    [Install]
    WantedBy=default.target

I get the error "Usage: udiskie [options]..."

If I remove `--disable-notify`, then it works. It took me a long trial and error to pinpoint this issue. Please see if this service file is problematic for you as well.

Thanks.

**Comment by coldfix** [comment]
The correct command line option is `--no-notify`. Is `--disable-notify` documented somewhere? udiskie is right to break here, to tell you that your command line is incorrect.

Best, Thomas

**Comment by mindstormer12** [comment]
Yea, `--disable-notify` is in the man page of Arch's udiskie package, version 1.5.1-2. `--no-notify` does work.

**Comment by coldfix** [comment]
Oh you're right, I fixed it. I'll open a new thread for the other issue and have a closer look tomorrow. Thanks!
