### ISSUE TITLE
No mount point for LUKS encrypted drive

### ISSUE THREAD

**Issue by siftra** [coldfix/udiskie#133]
I am not sure if I am missing something, but I am unable to access my encrypted hard drive (`sdb1`) after entering the password for it due to no mount point. `lsblk` returns (I apologize for the messy output; Github deletes white-space when I turn it into code so I turned spaces into underscores):
`NAME__________________________________________MAJ:MIN_RM___SIZE_RO_TYPE_MOUNTPOINT`
`sda_____________________________________________8:0____0_238.5G__0_disk  `
`├─sda1__________________________________________8:1____0___1.5G__0_part  `
`├─sda2__________________________________________8:2____0___100G__0_part  `
`├─sda3__________________________________________8:3____0____16G__0_part  `
`└─sda4__________________________________________8:4____0___114G__0_part_/`
`sdb_____________________________________________8:16___1_111.8G__0_disk  `
`└─sdb1__________________________________________8:17___1_111.8G__0_part  `
`__└─luks-8ab5b316-b1d1-4c1c-8597-7a164e49b307_254:0____0_111.8G__0_crypt`

From the output, it does not specify that there is a mount point. Does it need to be specified when entering `udiskie-mount  /dev/sdb1`? I tried mounting a USB flash drive and it automatically mounted to the `/media` folder so I am not sure how to proceed. Here's the verbose output as I mount the encrypted drive, if it is of any help:
```
DEBUG [2017-01-27 21:54:09,366] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/ekai/.config/udiskie/config.yml'
DEBUG [2017-01-27 21:54:09,368] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/ekai/.config/udiskie/config.json'
DEBUG [2017-01-27 21:54:09,394] udiskie.config: IgnoreDevice(match={'symlinks': '/dev/mapper/docker-*'}, value=True) created
DEBUG [2017-01-27 21:54:09,394] udiskie.config: IgnoreDevice(match={'symlinks': '/dev/disk/by-id/dm-name-docker-*'}, value=True) created
DEBUG [2017-01-27 21:54:09,394] udiskie.config: IgnoreDevice(match={'is_loop': True, 'loop_file': '/*'}, value=False) created
DEBUG [2017-01-27 21:54:09,394] udiskie.config: IgnoreDevice(match={'is_block': False}, value=True) created
DEBUG [2017-01-27 21:54:09,395] udiskie.config: IgnoreDevice(match={'is_external': False}, value=True) created
DEBUG [2017-01-27 21:54:09,395] udiskie.config: IgnoreDevice(match={'is_ignored': True}, value=True) created
DEBUG [2017-01-27 21:54:09,395] udiskie.udisks2: found device owning "/dev/sdb1": "/org/freedesktop/UDisks2/block_devices/sdb1"
```
Thank you!

**Comment by coldfix** [comment]
Hey,

to enter code/log blocks, just surround the entire paragraph with three backticks (` ``` `) as described [here](https://help.github.com/articles/creating-and-highlighting-code-blocks/) and nobody will delete your spaces.

The log you showed doesn't look complete. In particular, it doesn't show what happens when/after you enter your password etc.

With what filesystem did you format your drive? Do you succeed in unlocking + mounting manually, i.e.

```
cryptsetup open /dev/sdb1 encrypted
mount /dev/mapper/encrypted /mnt
```

Can you show the information obtained from `udisksctl info -b /dev/sdb1` and/or the unlocked crypto partition?

Best, Thomas

**Comment by siftra** [comment]
Hello,
Thank you for the advice! 
The command `cryptsetup open /dev/sdb1 encrypted` does allow me to unlock it and the command `sudo mount /dev/sdb1 /mnt` did set the mountpoint to `/mnt` (as the command indicates):
Here's the output of `lsblk`:

```
NAME          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda             8:0    0 238.5G  0 disk  
├─sda1          8:1    0   1.5G  0 part  
├─sda2          8:2    0   100G  0 part  
├─sda3          8:3    0    16G  0 part  
└─sda4          8:4    0   114G  0 part  /
sdb             8:16   1 111.8G  0 disk  
└─sdb1          8:17   1 111.8G  0 part  
  └─encrypted 254:0    0 111.8G  0 crypt /mnt

```
Here's the info obtained from `udisksctl info -b /dev/sdb1`:
```
/org/freedesktop/UDisks2/block_devices/sdb1:
  org.freedesktop.UDisks2.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/sdb1
    DeviceNumber:               2065
    Drive:                      '/org/freedesktop/UDisks2/drives/SanDisk_Ext_SSD_154520400588'
    HintAuto:                   true
    HintIconName:               
    HintIgnore:                 false
    HintName:                   
    HintPartitionable:          true
    HintSymbolicIconName:       
    HintSystem:                 false
    Id:                         by-uuid-8ab5b316-b1d1-4c1c-8597-7a164e49b307
    IdLabel:                    
    IdType:                     crypto_LUKS
    IdUUID:                     8ab5b316-b1d1-4c1c-8597-7a164e49b307
    IdUsage:                    crypto
    IdVersion:                  1
    MDRaid:                     '/'
    MDRaidMember:               '/'
    PreferredDevice:            /dev/sdb1
    ReadOnly:                   false
    Size:                       120033058304
    Symlinks:                   /dev/disk/by-id/usb-SanDisk_Ext_SSD_154520400588-0:0-part1
                                /dev/disk/by-partuuid/aa7a443f-3b57-4614-b6e0-986b93f55fb4
                                /dev/disk/by-path/pci-0000:00:14.0-usb-0:1:1.0-scsi-0:0:0:0-part1
                                /dev/disk/by-uuid/8ab5b316-b1d1-4c1c-8597-7a164e49b307
  org.freedesktop.UDisks2.Encrypted:
  org.freedesktop.UDisks2.Partition:
    Flags:              0
    IsContained:        false
    IsContainer:        false
    Name:               
    Number:             1
    Offset:             1048576
    Size:               120033058304
    Table:              '/org/freedesktop/UDisks2/block_devices/sdb'
    Type:               0fc63daf-8483-4772-8e79-3d69d8477de4
    UUID:               aa7a443f-3b57-4614-b6e0-986b93f55fb4

```
Thank you for providing me with those commands. Would it possible to achieve the same effect with the `"udiskie-mount"` command?

**Comment by coldfix** [comment]
Hey,

now that you mention the `udiskie-mount`, I have the suspicion you tried with this command rather than the automount daemon. In this case, you have to tell udiskie to mount *recursively*, i.e. mount after unlocking:

```
udiskie-mount -r /dev/sdb1
```

Alternatively, you can `udiskie-mount` the unlocked partition in a second step manually.

Did this solve your issue?

**Comment by siftra** [comment]
Yes, thank you so much!
