### ISSUE TITLE
udiskie mount LUKS-encrypted folder name

### ISSUE THREAD

**Issue by rieje** [coldfix/udiskie#134]
Not sure if it's udiskie or something else, but when I plug in my external LUKS-encrypted HDD and it auto-prompts me for passphrase, after I enter it, it gets mounted to `/media/<some_seemingly_random_string>`. `Also, the /dev/mapper is /<luks-#################>`. How change both of these names to something more sensible?

Much appreciated.

**Comment by coldfix** [comment]
udiskie has no control over mount name. This responsibility is entirely in the scope of udisks. It is expected that an ID appears in the `/dev/mapper/` device name. However, if you have assigned a label to the formatted file system, udisks will automatically detect the correct label and mount under that name.
