### ISSUE TITLE
Mountpoint folder not automatically deleted when shutting down system

### ISSUE THREAD

**Issue by rieje** [coldfix/udiskie#137]
Not sure if this is expected behavior because udiskie is just an automounter, but often when I shut down the system without manually unmounting and/or locking an external drive that is LUKS-encrypted, the mountpoint folder will not be removed. For example, if I plug in the drive and it gets mounted to `/media/external_HDD` automatically, then `/media/external_HDD` will not be removed when the drive is not manually unmounted and/or locked (if it is, it gets automatically removed). 

This is important because if the folder is not removed, then the next time the drive gets mounted, it will mount to `/media/external_HDD1` instead. I would have to unmount this mountpoint, and remove both `/media/external_HDD` and `/media/external_HDD1` so mounting back the drive will mount to the correct `/media/external_HDD`.

I assume the system unmounts and locks the HDD safely when shutting down the system, but this mountpoint folder is not deleted (not the system's responsibility). Is this behavior expected and is there a way to deal with it nicely? 

Or are udiskie users simply required to manually dismount the drive in order for the mountpoint folder to be removed? Otherwise, the folder needs to be manually deleted with root permissions.

Thanks.

**Comment by coldfix** [comment]
Hey. You're not the first to notice this, see #104. It's not possible to implement this on the level of udiskie (runs as user). Can you report to [udisks](https://github.com/storaged-project/udisks)?

**Comment by coldfix** [comment]
I think udisks should just reuse empty folders when mounting devices. Not sure whether they like it.

**Comment by rieje** [comment]
Thanks. Did you found there to be any caveats with the [workaround](https://github.com/coldfix/udiskie/wiki/Miscellaneous)?

**Comment by coldfix** [comment]
In the end, I was too lazy to use the workaround.. I can't think of any problems, except if you by accident move files into the folder.
