### ISSUE TITLE
Documentation unclear on handling LUKS automount

### ISSUE THREAD

**Issue by embik** [coldfix/udiskie#139]
I feel like I might be to stupid to find the documentation, but it feels like the man page (and other docs) are unclear on how to handle automounting LUKS devices. There seem to be no examples and I have little to no idea how to configure it, either with a password or a key file. There's a LUKS encrypted partition at /dev/sda1, how do I configure "hands-off" automounting for it?

**Comment by coldfix** [comment]
Hi, you're right, the documentation is a bit thin here, sorry.

If you want to automount using a LUKS device, see #66, specifically [the last comment](https://github.com/coldfix/udiskie/issues/66#issuecomment-289204539).

**Comment by embik** [comment]
I'm actually looking _for_ automounting, but the keyfile approach looks good. Thanks, I'll try it out!

**Comment by coldfix** [comment]
> Any way to set the mapper name used for the decrypted partition?

You can specify it in your `crypttab` (needs root access), otherwise currently no, see https://github.com/storaged-project/udisks/blob/master/src/udiskslinuxencrypted.c#L411.

**Comment by embik** [comment]
Alright, I got automount to work (although udisks doesn't use the name from crypttab for some reason). Thanks! Adding this information to the manpage should be easy, I'll try to work on a PR for that.
