### ISSUE TITLE
Cannot mount device by UUID using config.yml

### ISSUE THREAD

**Issue by anno2100** [coldfix/udiskie#142]
I'm currently using udiskie 1.7.0 on my Arch system with i3wm. 
When I start it with "udiskie -a &" it perfectly mounts all devices.
But I'd like to not automount all devices but only one device by UUID.
I have an external HDD with two partitions, one is for my backups which I would like to automount.

Therefore I want to start udiskie like this: "udiskie -c ~/.config/udiskie/config.yml &"
Unfortunately I can't get it to work. 

This is my config.yml:

```
program_options:
# Configure defaults for command line options
     tray:             auto    # [bool] Enable the tray icon. "auto"
                             # means auto-hide the tray icon when
                             # there are no handled devices.
    menu:             nested  # ["flat" | "nested"] Set the
                             # systray menu behaviour.
    automount:        false   # [bool] Enable automatic mounting.
    notify:           false    # [bool] Enable notifications.
 
 
 device_config: 
 - id_uuid: UUID_OF_MY_PARTITION        # [filter] match by device UUID
   options: [noexec, nodev]  # [action] mount options can be given as list
   ignore:  false            # [action] never ignore this device (even if fs=FAT)
   automount: true           # [action] do automount this device
```

This is the output if I start udiskie in verbose mode:

> DEBUG [2017-06-18 17:04:31,607] udiskie.udisks2: Daemon version: 2.6.5
DEBUG [2017-06-18 17:04:31,784] udiskie.config: DeviceFilter(match={'id_uuid': 'UUID_OF_MY_PARTITION '}, value={'options': ['noexec', 'nodev'], 'ignore': False, 'automount': True}) created
DEBUG [2017-06-18 17:04:31,784] udiskie.config: IgnoreDevice(match={'symlinks': '/dev/mapper/docker-*'}, value={'ignore': True}) created
DEBUG [2017-06-18 17:04:31,784] udiskie.config: IgnoreDevice(match={'symlinks': '/dev/disk/by-id/dm-name-docker-*'}, value={'ignore': True}) created
DEBUG [2017-06-18 17:04:31,784] udiskie.config: IgnoreDevice(match={'is_loop': True, 'loop_file': '/*'}, value={'ignore': False}) created
DEBUG [2017-06-18 17:04:31,784] udiskie.config: IgnoreDevice(match={'is_block': False}, value={'ignore': True}) created
DEBUG [2017-06-18 17:04:31,784] udiskie.config: IgnoreDevice(match={'is_external': False}, value={'ignore': True}) created
DEBUG [2017-06-18 17:04:31,784] udiskie.config: IgnoreDevice(match={'is_ignored': True}, value={'ignore': True}) created
DEBUG [2017-06-18 17:04:31,786] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/nvme0n1p1
DEBUG [2017-06-18 17:04:31,786] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/nvme0n1p2
DEBUG [2017-06-18 17:04:31,786] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/nvme0n1p3
DEBUG [2017-06-18 17:04:31,786] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/dm_2d0
DEBUG [2017-06-18 17:04:31,787] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/dm_2d1
DEBUG [2017-06-18 17:04:31,787] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/dm_2d2
DEBUG [2017-06-18 17:04:31,787] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/dm_2d3
DEBUG [2017-06-18 17:04:31,787] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/dm_2d4
DEBUG [2017-06-18 17:04:31,787] udiskie.config: IgnoreDevice(match={'is_block': False}, ignore=True) used for /org/freedesktop/UDisks2/drives/S2CYNX0H904467
DEBUG [2017-06-18 17:04:31,788] udiskie.config: DeviceFilter(match={'id_uuid': 'UUID_OF_MY_PARTITION '}, ignore=False) used for /org/freedesktop/UDisks2/block_devices/sda1
DEBUG [2017-06-18 17:04:31,788] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/nvme0n1
DEBUG [2017-06-18 17:04:31,788] udiskie.config: IgnoreDevice(match={'is_block': False}, ignore=True) used for /org/freedesktop/UDisks2/drives/TOSHIBA_MQ01UBD100_43N1T7KBT
DEBUG [2017-06-18 17:04:31,828] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/nvme0n1p1
DEBUG [2017-06-18 17:04:31,829] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/nvme0n1p2
DEBUG [2017-06-18 17:04:31,829] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/nvme0n1p3
DEBUG [2017-06-18 17:04:31,829] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/dm_2d0
DEBUG [2017-06-18 17:04:31,830] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/dm_2d1
DEBUG [2017-06-18 17:04:31,830] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/dm_2d2
DEBUG [2017-06-18 17:04:31,830] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/dm_2d3
DEBUG [2017-06-18 17:04:31,830] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/dm_2d4
DEBUG [2017-06-18 17:04:31,831] udiskie.config: IgnoreDevice(match={'is_block': False}, ignore=True) used for /org/freedesktop/UDisks2/drives/S2CYNX0H904467
DEBUG [2017-06-18 17:04:31,831] udiskie.config: DeviceFilter(match={'id_uuid': 'UUID_OF_MY_PARTITION '}, ignore=False) used for /org/freedesktop/UDisks2/block_devices/sda1
DEBUG [2017-06-18 17:04:31,831] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/nvme0n1
DEBUG [2017-06-18 17:04:31,832] udiskie.config: IgnoreDevice(match={'is_block': False}, ignore=True) used for /org/freedesktop/UDisks2/drives/TOSHIBA_MQ01UBD100_43N1T7KBT

I hope I don't have any silly mistake in my config file. Would greatly appreciate any help and will gladly provide any more information needed and help debug whether it's a human or an udiskie error.

**Comment by coldfix** [comment]
Hi,

sorry, the documentation/name of the options are a bit unclear hear:

```
program_options:
 automount: false
```

disables automounting completely, so the other rule won't have a chance to kick in.

If you just want to enable a single device, leave it as true and set the following:

```
 device_config: 
 - id_uuid: UUID_OF_MY_PARTITION
   ...
   automount: true           # [action] do automount this device
- automount: false
```

Does this help?

**Comment by anno2100** [comment]
Thank you for your fast reply. 
I misinterpreted this line: " The rules defined here are simply prepended to the builtin device rules,.."
I thought the rules after device_config would overwrite the rules in program_options. 
With your change it now all works as I wanted. Thanks a lot!

The issue can be closed.

(The indentation was correct in my file, somehow it changed while copy-pasting it here.
