### ISSUE TITLE
udiskie-info gives duplicate inconsistent entries

### ISSUE THREAD

**Issue by fogine** [coldfix/udiskie#145]
Hello, I have been using `udiskie-info` in my dmenu script and noticed that when manipulating with Luks encrypted devices, `udiskie-info` dumps:

Example after unmouting encrypted luks device `sdd1`:

```bash
> udiskie-info -C -2 -a -o '"label":"{ui_label}", "isLuks":"{is_luks}", "mountPath": "{mount_path}"'

"label":"/dev/sdd1: sdd1uilabel", "isLuks":"False", "mountPath": ""
"label":"/dev/sdc: sdcuilabel", "isLuks":"False", "mountPath": ""
"label":"/dev/sdc1: sdc1uilabel", "isLuks":"True", "mountPath": ""
"label":"/dev/sdd: sdduilabel", "isLuks":"False", "mountPath": ""
"label":"/dev/sdd1: sdd1uilabel", "isLuks":"True", "mountPath": ""
"label":"/dev/sdd2: sdd2uilabel", "isLuks":"False", "mountPath": "/run/media/myuser/sdd2uilabel"
```

Notice that `sdd1` is present twice in the output.

Example of output after mounting encrypted luks device `sdc1`:

```bash
> udiskie-info -C -2 -a -o '"label":"{ui_label}", "isLuks":"{is_luks}", "mountPath": "{mount_path}"'

"label":"/dev/sdc1: sdc1uilabel", "isLuks":"False", "mountPath": "/run/media/myuser/sdc1uilabel"
"label":"/dev/sdd1: sdd1uilabel", "isLuks":"False", "mountPath": ""
"label":"/dev/sdc: sdcuilabel", "isLuks":"False", "mountPath": ""
"label":"/dev/sdc1: sdc1uilabel", "isLuks":"True", "mountPath": ""
"label":"/dev/sdd: sdduilabel", "isLuks":"False", "mountPath": ""
"label":"/dev/sdd1: sdd1uilabel", "isLuks":"True", "mountPath": ""
```

Notice that the `isLuks` value differs in the duplicates.

Is this expected behavior?

**Comment by coldfix** [comment]
Hi, I chose to use `/dev/sdd1` type strings even for the unlocked cleartext devices, because I thought this would be less confusing in the GUI. This is as expected. If you want the real block device, use `device_presentation` or `device_file` rather than `ui_label`.

Let me know if this works for you. Best, Thomas

**Comment by fogine** [comment]
I see.. makes sense.
Cheers!
