### ISSUE TITLE
PyPi Relase of 1.7.2

### ISSUE THREAD

**Issue by embik** [coldfix/udiskie#150]
Hey there,

I noticed 1.7.2 hasn't been uploaded to PyPi yet. My Gentoo ebuild pulls from PyPi and obviously fails when trying to build 1.7.2.

Are releases still expected to be on PyPi or should I point my ebuild just straight to GitHub's tarballs?

**Comment by coldfix** [comment]
Thanks! I upladed it to PyPI. Sometimes I forget to upload either pypi or github, sorry.

**Comment by embik** [comment]
No problem, thank you very much!
