### ISSUE TITLE
I can't get udiskie to execute a command/launch a file manager on mount

### ISSUE THREAD

**Issue by wessm** [coldfix/udiskie#151]
For some reason udiskie won't start my new terminal window/does not execute the command on mount. The debug output shows no errors and is also not complaining that the executable is not found.

my config.yml

           # Configure defaults for command line options

             udisks_version:   2       # [int] Specify the version of udisks
                                       # to be used. Set to 0 to use automatic
                                       # discovery.

             tray:             auto    # [bool] Enable the tray icon. "auto"
                                       # means auto-hide the tray icon when
                                       # there are no handled devices.

             automount:        true   # [bool] Enable automatic mounting.

             notify:           false    # [bool] Enable notifications.

             password_cache:   30      # [int] Password cache in minutes. Caching is
                                       # disabled by default. It can be disabled
                                       # explicitly by setting it to false

             file_manager:     "/home/mischa/bin/start_term.sh"
               # [string] Set program to open directories. It will be invoked
               # with the folder path as its # command line first argument.

             password_prompt: ["gnome-keyring-query", "get", "{.id_uuid}"]
               # [string|list] Set command to retrieve passwords. If specified
               # as a list it defines the ARGV array for the program call. If
               # specified as a string, it will be expanded in a shell-like
               # manner. Each string will be formatted using str.format with a
               # Device object as the first argument. For a list of device
               # attributes, see below. The two special string values
               # "builtin:gui" and "builtin:tty" signify to use udiskie's
               # builtin password prompt.

           mount_options:
             # List of mount option rules. Only the first matching entry is
             # used. Each item can match any combination of device attributes
             # (see below). Additionally, it must define an 'options' list. An
             # item without any device attributes serves as a catch-all rule.

           - id_type: vfat             # match file system type
             options: ro               # list of mount options
           - id_uuid: 9d53-13ba        # match by device UUID
             options: [noexec, nodev]  # mount options can be given as list

           ignore_device:
             # Customize udiskie's ignore rules. This config entry has the
             # same structure as *mount_options*, the only difference being
             # that the action is defined by the 'ignore' field which is a
             # boolean defaulting to true. The rules defined here are simply
             # prepended to the builtin ignore rules, so that it is possible
             # to completely overwrite the defaults by specifying a catch-all
             # rule.

           - id_uuid:     abcd-ef01    # ignore this device
           - device_file: /dev/dm-5
             ignore:      false /home/mischa/bin/start_term.sh       # never ignore this device

           notifications:
             # Customize which notifications are shown for how long. Possible
             # values are:
             #   positive number         timeout in seconds
             #   false                   disable
             #   -1                      use the libnotify default timeout

             timeout:          1.5     # set the default for all notifications

             # Specify only if you want to overwrite the the default:
             device_mounted:   5       # mount notification
             device_unmounted: false   # unmount notification
             device_added:     false   # device has appeared
             device_removed:   false   # device has disappeared
             device_unlocked:  -1      # encrypted device was unlocked
             device_locked:    -1      # encrypted device was locked
             job_failed:       -1      # mount/unlock/.. has failed

           notification_actions:
             # Define which actions should be shown on notifications. Note that there
             # are currently only a limited set of actions available for each
             # notification. Events that are not explicitly specified show the default
             # set of actions. Specify an empty list if you don't want to see any
             # notification for the specified event:

             device_mounted:   [browse]
             device_added:     [mount]

           icon_names:
             # Customize the icon set used by the tray widget. Each entry
             # specifies a list of icon names. The first installed icon from
             # that list will be used.

             media:   [drive-removable-media, media-optical]
             browse:  [document-open, folder-open]
             mount:   [udiskie-/home/mischa/bin/start_term.shmount]
             unmount: [udiskie-unmount]
             unlock:  [udiskie-unlock]
             lock:    [udiskie-lock]
             eject:   [udiskie-eject, media-eject]
             detach:  [udiskie-detach]
             quit:    [application-exit]

`/home/mischa/bin/start_term.sh`is a shell script that opens a new terminal window at the given folder, it works perfectly well from the command line. Does anyone know what the problem might be? Im running udiskie 1.7.2.

**Comment by coldfix** [comment]
Show me `start_term.sh` please.

**Comment by coldfix** [comment]
Can you add something like `(date; echo $DISPLAY) >> /home/mischa/foo` to the top, to see if the script gets executed at all:

If yes: do you execute udiskie from any special environment (systemd, cron, ...)? What is the value of $DISPLAY? Does it actually start a new terminal or just execute a program assuming it is already inside a terminal?

If no: is the script executable?

**Comment by wessm** [comment]
Hi, thanks for your fast response!

start_term.sh is executable (running it from the command line works!) and looks like that: 

    #!/bin/bash
    (date; echo $DISPLAY) >> /home/mischa/foo
    rxvt-unicode -cd "$@" &

looks like its not running at all, since the line I added didn't do anything.

I just run udiskie from another terminal, it correctly auto-mounts the drives.

$DISPLAY is ".0"

**Comment by coldfix** [comment]
Hi, thanks for the info.

Silly question: do you select "Browse XXXX" from the menu or the notification? (udiskie doesn't automatically trigger the action on mount)

**Comment by wessm** [comment]
> udiskie doesn't automatically trigger the action on mount

Ok, then I guess I know what the problem is; that was exactly what I thought it will do!
I use udiskie on i3 without the tray icon or the notifications, I really thought it will be triggered automatically on mount!

My bad; will look into the notifications!

**Comment by coldfix** [comment]
If you want an automatic trigger, you need the `notify_command` option. This also runs on other events, but you could sort it out inside your script.

Example config:

```
program_options:
  notify_command: "/home/mischa/bin/udiskie_event.sh {event} {device_presentation}"
```

and in your shell script check for `device_mounted` as first parameter.

Best, Thomas
