### ISSUE TITLE
udiskie shows internal raid

### ISSUE THREAD

**Issue by tiiiecherle** [coldfix/udiskie#155]
Hey,

first of all thanks for this nice software.

On our server udiskie shows an internal encrypted raid. This 

```
UUID_SDA1=$(udiskie-info -o '{id_uuid}' /dev/sda1)
mkdir -p /home/$USER/.config/udiskie
touch /home/$USER/.config/udiskie/config.yml
cat > /home/$USER/.config/udiskie/config.yml << EOF
device_config:
  - device_file: /dev/sda
    ignore: true
  - id_uuid: $UUID_SDA1
    ignore: true
EOF
```

helps not showing /dev/sda any more, but /dev/sda1 is still shown.

UUID_SDA1 is different from the number shown next to /dev/sda1 in udiskie.

Thanks for the help in advance.

Kind regards

**Comment by coldfix** [comment]
Hi,

I would guess that your config suppresses the crypto-device but udiskie fails to also ignore its associated plaintext devices as well. Try ignoring the plaintext device as well by adding its UUID too.

You can use `udisksctl dump` to get a comprehensive overview of all devices known to udisks.  Can you please post the relevant parts of the output? Normally udiskie should ignore child devices if you ignore their parents, but this may not be working the same way for RAID or LVM devices.

Best, Thomas

**Comment by tiiiecherle** [comment]
Thanks, this is the sda1 output:

```
/org/freedesktop/UDisks2/block_devices/dm_2d6:
  org.freedesktop.UDisks2.Block:
    Configuration:              [('fstab', {'fsname': <b'/dev/mapper/data_encrypted'>, 'dir': <b'/data'>, 'type': <b'ext4'>, 'opts': <b'rw,relatime,data=ordered'>, 'freq': <0>, 'passno': <2>})]
    CryptoBackingDevice:        '/org/freedesktop/UDisks2/block_devices/sda1'
    Device:                     /dev/dm-6
    DeviceNumber:               65030
    Drive:                      '/'
    HintAuto:                   false
    HintIconName:               
    HintIgnore:                 false
    HintName:                   
    HintPartitionable:          false
    HintSymbolicIconName:       
    HintSystem:                 true
    Id:                         by-id-dm-name-data_encrypted
    IdLabel:                    
    IdType:                     ext4
    IdUUID:                     1441fcfa-3e10-41cf-935b-e2e02865091b
    IdUsage:                    filesystem
    IdVersion:                  1.0
    MDRaid:                     '/'
    MDRaidMember:               '/'
    PreferredDevice:            /dev/mapper/data_encrypted
    ReadOnly:                   false
    Size:                       5991464697856
    Symlinks:                   /dev/disk/by-id/dm-name-data_encrypted
                                /dev/disk/by-id/dm-uuid-CRYPT-LUKS1-82ac04c3e1574bf299ccf3aa3ba553ae-data_encrypted
                                /dev/disk/by-uuid/1441fcfa-3e10-41cf-935b-e2e02865091b
                                /dev/mapper/data_encrypted
    UserspaceMountOptions:      
  org.freedesktop.UDisks2.Filesystem:
    MountPoints:        /data
    Size:               5991464697856
```

I recognized one mistake:
`udiskie-info -o '{id_uuid}' /dev/sda1`
was giving me 82ac04c3e1574bf299ccf3aa3ba553ae instead of 1441fcfa-3e10-41cf-935b-e2e02865091b.

When using
```
device_config:
  - device_file: /dev/sda
    ignore: true
  - id_uuid: 1441fcfa-3e10-41cf-935b-e2e02865091b
    ignore: true
```
in the config file, it gets better. But there are still two lines left:
/dev/sda1: 1441fcfa-3e10-41cf-935b-e2e02865091b (greyed out)
and
Lock /dev/sda1: 1441fcfa-3e10-41cf-935b-e2e02865091b.

So the device is still not ignored completely. Would be nice to have further help. Thanks

**Comment by coldfix** [comment]
Ignore both

- the crypto device `82ac04c3e1574bf299ccf3aa3ba553ae` (`/dev/sda1`) that contains the raw encrypted data
- *and* the plaintext device `1441fcfa-3e10-41cf-935b-e2e02865091b` (`/dev/dm-6`) that is a virtual device containing the decrypted data

these are treated as two separate devices.

**Comment by tiiiecherle** [comment]
this is working perfectly now:

```
SDX_DATA=$(ls -la /dev/disk/by-partlabel/ | grep data | awk '{print $NF}' | rev | cut -d'/' -f1 | rev | sed 's/[0-9]$//')
UUID_SDX1=$(udiskie-info -o '{id_uuid}' /dev/"$SDX_DATA"1)
UUID_SDX1_MAPPER=$(udiskie-info -o '{id_uuid}' /dev/mapper/data_encrypted)
mkdir -p /home/$USER/.config/udiskie
touch /home/$USER/.config/udiskie/config.yml
cat > /home/$USER/.config/udiskie/config.yml << EOF
device_config:
  - device_file: /dev/$SDX_DATA
    ignore: true
  - id_uuid: $UUID_SDX1
    ignore: true
  - id_uuid: $UUID_SDX1_MAPPER
    ignore: true
EOF
```

Thanks for the help. Is there a better way to find /dev/sda from /dev/mapper/data_encrypted as user without lvm tools that need root?

**Comment by coldfix** [comment]
> this is working perfectly now:

Great.

> Is there a better way to find /dev/sda from /dev/mapper/data_encrypted as user without lvm tools that need root?

`udisksctl dump` or `udisksctl info -b /dev/mapper/data_encrypted`. Look at the second entry `CryptoBackingDevice` and track from there.

There is also a property in udiskie but I forgot to clear it for access by user, so you can't get it from `udiskie-info` for now.
