### ISSUE TITLE
Imports without specifying versions

### ISSUE THREAD

**Issue by faminebadger** [coldfix/udiskie#157]
Running udiskie from a console, I get the following warning spam:

> /usr/lib64/python2.7/site-packages/udiskie/prompt.py:11: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/lib64/python2.7/site-packages/udiskie/cli.py:319: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify

This seems like a trivially fixable error.

**Comment by coldfix** [comment]
This should be fixed since udiskie 1.4 which is more than 2 years ago. Please reopen if you are running a more recent version.

**Comment by faminebadger** [comment]
Oh, sorry, I had no idea the package on gentoo was so out of date.  That's annoying - I'll have to get the latest source instead then.

Thanks.
