### ISSUE TITLE
Can't use "--options" with NTFS

### ISSUE THREAD

**Issue by alex3kov** [coldfix/udiskie#159]
```sh
udiskie-mount -o noatime /dev/sda1
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/udiskie/cli.py", line 307, in _start_async_tasks
    results = yield self._init()
  File "/usr/lib/python3.6/site-packages/udiskie/cli.py", line 619, in _init
    device_config._filters.insert(0, udiskie.config.MountOptions({
AttributeError: 'list' object has no attribute '_filters'
```
Same thing with `udiskie-mount --options=noatime /dev/sda1`. `/dev/sda1` is NTFS partition, not encrypted. No config file is used.

**Comment by coldfix** [comment]
Thanks! I have created a patch that should resolve the issue. I will test it later and create a small bugfix release.

Best, Thomas

**Comment by alex3kov** [comment]
Awesome, thanks! Is the patch only for "noatime"? I plan to play with several different options.

**Comment by coldfix** [comment]
This should fix the programming error inside udiskie and make it forward arbitrary options to udisks. Whether udisks knows to handle your options for NTFS devices is another question on the other hand.

**Comment by alex3kov** [comment]
I'll test it as soon as at hits Arch repo: https://www.archlinux.org/packages/community/any/udiskie/
There's no udiskie-git package in AUR, unfortunately.
