### ISSUE TITLE
Release changes on master/repository state

### ISSUE THREAD

**Issue by IvanMalison** [coldfix/udiskie#161]
Seems like there are quite a few changes on master waiting to be released. What is oging on here?

https://github.com/coldfix/udiskie/compare/1.7.5...master

**Comment by coldfix** [comment]
Hi, reasons include that I

- changed the underlying async framework to use asyncio/gbulb and wanted to wait and test before releasing
-  removed py2/udisks1 support and wanted to give time in the deprecation period
- wanted to throw in a couple more (backward incompatible) changes before doing the next major release
- didn't have time

**Comment by IvanMalison** [comment]
@coldfix Yeah but it seems like there was of rebase or something so that there are commits that have been changed on master.

**Comment by coldfix** [comment]
Please be more specific next time if there is a real issue. Closing this for now.
