### ISSUE TITLE
Cannot ignore device?

### ISSUE THREAD

**Issue by rieje** [coldfix/udiskie#168]
I have a script that runs `udiskie-umount --all && systemctl poweroff` to ensure the system does not shut down until all devices are properly unmounted so data integrity is preserved. `udiskie-umount --all` keeps returning `not locking /org/freedesktop/UDisks2/block_devices/sdd1: unhandled device` and failing with exit code 1. `sdd1` is a partition of a disk that's part of my RAID 1 setup and it's LUKS encrypted. 

In my config I have the following:

    device_config:
      - device_file: /dev/sdd1
        ignore: true 
      - id_uuid: d51a8388-acf2-458a-8a9c-c6d0d76221d8
        ignore: true

where `/dev/sdd1: UUID="d51a8388-acf2-458a-8a9c-c6d0d76221d8" TYPE="crypto_LUKS" PARTLABEL="Linux filesystem" PARTUUID="0eec9fe5-3109-4ba2-afbc-4255aa0f96a1"` is the output of `blkid`. Am I supposed to use the UUID of `/dev/mapper/container` instead? What am I doing wrong?

Much appreciated.

**Comment by coldfix** [comment]
Sorry for replying so extremely late.. 

I have identified the probable source of this error and the corresponding fix will be included in version 2.0 (no release date yet).

> I have a script that runs `udiskie-umount --all && systemctl poweroff` to ensure the system does not shut down until all devices are properly unmounted so data integrity is preserved.

I don't believe that's needed (but I can't guarantee, please let me know if you have actual info on this).

> `udiskie-umount --all` keeps returning `not locking /org/freedesktop/UDisks2/block_devices/sdd1: unhandled device` and failing with exit code 1.

It may be useful to turn on verbose mode (`udiskie -v`) to see which filters were used for what.

> `sdd1` is a partition of a disk that's part of my RAID 1 setup and it's LUKS encrypted.

RAID could be a problem, there is currently no special support implemented in udiskie.

> 
> In my config I have the following:
> 
> ```
> device_config:
>   - device_file: /dev/sdd1
>     ignore: true 
>   - id_uuid: d51a8388-acf2-458a-8a9c-c6d0d76221d8
>     ignore: true
> ```
> 
> where `/dev/sdd1: UUID="d51a8388-acf2-458a-8a9c-c6d0d76221d8" TYPE="crypto_LUKS" PARTLABEL="Linux filesystem" PARTUUID="0eec9fe5-3109-4ba2-afbc-4255aa0f96a1"` is the output of `blkid`. Am I supposed to use the UUID of `/dev/mapper/container` instead? What am I doing wrong?
> 
> Much appreciated.

Looks good to me. Did you try ignoring both in the meantime?
