### ISSUE TITLE
Mounting drive as rw

### ISSUE THREAD

**Issue by Munchotaur** [coldfix/udiskie#170]
I'm using udiskie on Devuan and it's automounting flash drives perfectly using udisks2.

However I can't see how to force the drives to mount as read/write rather than read only. Is this configurable via udiskie or do I have to do something in the PolKit rules or udisks2 options?

**Comment by srd424** [comment]
Not totally relevant, but this is one of the bugs I looked at trying to solve my problem, so in case someone else stumbles along here: the ntfs-3g driver doesn't pass ntfs-specific options through to `/etc/mtab` / `mount(8)` output, so it can look as if it has ignored requested options - you have to check the syslog output to see what it has actually done ..
