### ISSUE TITLE
Checking Permissions

### ISSUE THREAD

**Issue by CrashyBang** [coldfix/udiskie#173]
Is there a command I can run to see whether or not my DM/DE has loaded the correct permissions as outline [here](https://github.com/coldfix/udiskie/wiki/Permissions).

I am having trouble getting up and running on Void Linux and trying to identify the problem, I think it may be to do with permissions.

**Comment by coldfix** [comment]
Does this page help?:

https://github.com/coldfix/udiskie/wiki/Debug-Info#polkit-for-permissions-problems

**Comment by CrashyBang** [comment]
Hey @coldfix yeah sorry I figured it out it was to do with file permissions, sorry should have updated here.
