### ISSUE TITLE
Not showing notifications, even cant mount

### ISSUE THREAD

**Issue by kyych** [coldfix/udiskie#174]
I encountered some problems. Main is that udiskie without sudo/root doesnt want to show notification. It just shows `Failed to show notification: Error calling StartServiceByName for org.freedesktop.Notifications: Timeout was reached` and after some time (like 50 seconds) mount usb drive. I am using i3-gaps and dunst, so it would be great to start udiskie from xinitrc without calling it from sudo manually.
I installed it with pip3 if it matters.
Can anyone help?

**Comment by coldfix** [comment]
This seems weird. I assume something on your system is broken with dbus permissions to spawn the notification daemon. Can you create notifications manually (e.g. using `notify-send`)?

**Comment by Migacz85** [comment]
I have exactly the same issue. Did you found out what was the reason ?

**Comment by coldfix** [comment]
Can you send notifications with `notify-send`?

(please don't use sudo for udiskie)

**Comment by coldfix** [comment]
`notify-send hi`

**Comment by Migacz85** [comment]
yup working

**Comment by coldfix** [comment]
Does this help: https://bbs.archlinux.org/viewtopic.php?pid=1564370#p1564370

> Try sourcing `/etc/X11/xinit/xinitrc.d/50-systemd-user.sh` from your xinit.

**Comment by Migacz85** [comment]
Same story.
![image](https://user-images.githubusercontent.com/25789997/56205032-9c6be180-6040-11e9-8c61-cd85540d15d4.png)
I write this to this file and launch new console to check this.

**Comment by coldfix** [comment]
Did you restart your window manager?

**Comment by coldfix** [comment]
And can you show `cat ~/.xinitrc`  or from  where do you launch your window manager?

**Comment by Migacz85** [comment]
![image](https://user-images.githubusercontent.com/25789997/56206127-8a3f7280-6043-11e9-9ea0-6852da9cef8b.png)
yup I restarted it. But this is strange. (this is just a side note) I have installed i3wm on KDE, and it looks like .xnitrc is completly not used here. Even that I have default session setup to i3 is still logging first KDE.

**Comment by coldfix** [comment]
The screenshot doesn't cover the whole file, why not just post the output of `cat ~/.xinitrc` as code?

> it looks like .xnitrc is completly not used here

Yes, if you start your session through a display manager or similar, it may ignore the file. In this case consult the docs of your displaymanager/desktop environment.

The original author implied he was starting it through xinitrc, so I assumed it applied to you as well.

**Comment by Migacz85** [comment]
Ok, I throw away kde completly and I'm starting i3wm from `.xinitrc` 
Warnings disapear, but still same issue. 

```bash
#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

exec i3
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

DEFAULT_SESSION=exec $1

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

get_session(){
	local dbus_args=(--sh-syntax --exit-with-session)
	case $1 in
		awesome) dbus_args+=(awesome) ;;
		bspwm) dbus_args+=(bspwm-session) ;;
		budgie) dbus_args+=(budgie-desktop) ;;
		cinnamon) dbus_args+=(cinnamon-session) ;;
		deepin) dbus_args+=(startdde) ;;
		enlightenment) dbus_args+=(enlightenment_start) ;;
		fluxbox) dbus_args+=(startfluxbox) ;;
		gnome) dbus_args+=(gnome-session) ;;
		i3|i3wm) dbus_args+=(i3 --shmlog-size 0) ;;
		jwm) dbus_args+=(jwm) ;;
		kde) dbus_args+=(startkde) ;;
		lxde) dbus_args+=(startlxde) ;;
		lxqt) dbus_args+=(lxqt-session) ;;
		mate) dbus_args+=(mate-session) ;;
		xfce) dbus_args+=(xfce4-session) ;;
		openbox) dbus_args+=(openbox-session) ;;
		*) dbus_args+=($DEFAULT_SESSION) ;;
	esac

	echo "dbus-launch ${dbus_args[*]}"
}

exec $(get_session)
xset r rate 600 25
exec $1

```

**Comment by Migacz85** [comment]
And after this tricks, (previously notify was sending hi) notify is Not sending 'Hi' but I have something like this:
![image](https://user-images.githubusercontent.com/25789997/56216872-23798380-605a-11e9-88ee-c15f3027c5d7.png)

**Comment by coldfix** [comment]
Your .xinitrc contains errors. Most importantly `exec` replaces the current process with whatever the rest of the command line is. This means, nothing is executed after the first `exec i3` line.

The script should look like this:

```bash
# prepare environment
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# settings
# xrdb, xmodmap, etc

# [ autostart other stuff]
udiskie &

# last line in the script:
exec i3
```

**Comment by coldfix** [comment]
For reference, my `.xinitrc` looks like this:


```bash
#! /bin/bash

export XSESSION=${1-awesome}

# load .Xresources
for Xresources in /etc/X11/xinit/.Xresources "$HOME/.Xresources"; do 
    [ -f "$Xresources" ] && xrdb -merge "$Xresources"
done


# load modmap *after* loading default keyboard layout
# see also: /usr/share/X11/xkb/rules/base.lst
setxkbmap -option caps:escape
setxkbmap cpp dvorak
for Xmodmap in /etc/X11/xinit/.Xmodmap "$HOME/.Xmodmap"; do 
    [ -f "$Xmodmap" ] && xmodmap "$Xmodmap"
done

# Source scripts in /etc/X11/xinit/xinitrc.d/
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for initrc in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$initrc" ] && . "$initrc"
    done
fi

# disable screensaver, mute audio on startup:
xset -dpms
xset s off
amixer -D pulse set Master mute

numlockx
wmname LG3D
# monitor auto
eval $(gpg-agent --daemon)
udiskie --tray &
kalu &
nm-applet &
pasystray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


# start anacron in user mode
local anacronfig=$HOME/.anacron
anacron -t $anacronfig/etc/anacrontab -S $anacronfig/spool & > $anacronfig/anacron.log

# execute WM
exec $XSESSION "${@:2}"
```

and I start awesome window manager with `startx`

**Comment by Migacz85** [comment]
```
#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh


userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# DEFAULT_SESSION=exec i3

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#     for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#         [ -x "$f" ] && . "$f"
#     done
#     unset f
# fi

exec udiskie -2 &

# get_session(){
# 	local dbus_args=(--sh-syntax --exit-with-session)
# 	case $1 in
# 		awesome) dbus_args+=(awesome) ;;
# 		bspwm) dbus_args+=(bspwm-session) ;;
# 		budgie) dbus_args+=(budgie-desktop) ;;
# 		cinnamon) dbus_args+=(cinnamon-session) ;;
# 		deepin) dbus_args+=(startdde) ;;
# 		enlightenment) dbus_args+=(enlightenment_start) ;;
# 		fluxbox) dbus_args+=(startfluxbox) ;;
# 		gnome) dbus_args+=(gnome-session) ;;
# 		i3|i3wm) dbus_args+=(i3 --shmlog-size 0) ;;
# 		jwm) dbus_args+=(jwm) ;;
# 		kde) dbus_args+=(startkde) ;;
# 		lxde) dbus_args+=(startlxde) ;;
# 		lxqt) dbus_args+=(lxqt-session) ;;
# 		mate) dbus_args+=(mate-session) ;;
# 		xfce) dbus_args+=(xfce4-session) ;;
# 		openbox) dbus_args+=(openbox-session) ;;
# 		*) dbus_args+=($DEFAULT_SESSION) ;;
# 	esac
# 	echo "dbus-launch ${dbus_args[*]}"
# }

# exec $(get_session)
# exec $1
# xset r rate 600 25

exec i3

```

I tried also something likg that. Notify don't work. To much time wasted today on this. I will came back to this some other day. Thanks

**Comment by Migacz85** [comment]
Is that `notify-send` function is only for sending information that drive is mounted?

**Comment by coldfix** [comment]
you still didn't take into account what told you about `exec`...

**Comment by coldfix** [comment]
Just use the exact .xinitrc from my previous example for a starting point:

```bash
# prepare environment
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# settings
# xrdb, xmodmap, etc

# [ autostart other stuff]
udiskie &

# last line in the script:
exec i3
```

and you would do well to learn some shell scripting if you are going to use linux.

**Comment by Migacz85** [comment]
I pasted exact .xinitrc and notify-send is not working.

**Comment by Migacz85** [comment]
Anyway - the whole purpose of  `notify-send` is just only for showing that disk is mounted and is not changing how the script is actually working when automount the drives ?

**Comment by coldfix** [comment]
Yes notifications are optional and don't influence the rest of the functionality.

However, `notify-send` is not internally used, udiskie directly instanciates notifications via the dbus api (and I would imagine notify-send does the same). I just mentioned `notify-send` to quickly determine whether it is a problem with udiskie itself or a general problem. The latter seems to be the case. 

> I pasted exact .xinitrc and notify-send is not working.

Depending on your system you might then also need dbus-launch, i.e. replace `exec i3` by `exec dbus-launch i3`.

Or just use without notifications.
