### ISSUE TITLE
Not automounting anymore? minus bang

### ISSUE THREAD

**Issue by ernie-cordell** [coldfix/udiskie#175]
I left this as a comment on a (seemingly) related issue, but I saw it was closed five years ago, so I'm dignifying it as an actual issue:  I installed from my standard package manager routine, but it worked before, so I didn't stop to see how it works. I'm trying some homework now, but it's a lot of catch-up for me --
My devices aren't getting automounted anymore: I'd suspect that I'm making a stupid mistake, but I haven't intentionally made any intentional changes (not that this excuses me). Here is the diagnostic help that occurs to me:

Linux linux-2lle.suse 4.4.165-81-default #1 SMP Mon Dec 3 07:47:23 UTC 2018 (0bfc9ed) x86_64 x86_64 x86_64 GNU/Linux
Traceback (most recent call last):
File "/usr/bin/udiskie", line 6, in 
from udiskie.cli import Daemon
File "/usr/lib/python3.4/site-packages/udiskie/cli.py", line 211
async def _start_async_tasks(self):
^
SyntaxError: invalid syntax
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model	: 23
model name	: Intel(R) Core(TM)2 Duo CPU P7350 @ 2.00GHz
stepping	: 6
microcode	: 0x60f
cpu MHz	: 2000.000
cache size	: 3072 KB
physical id	: 0
siblings	: 2
core id	: 0
cpu cores	: 2
apicid	: 0
initial apicid	: 0
fpu	: yes
fpu_exception	: yes
cpuid level	: 10
wp	: yes
flags	: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm sse4_1 lahf_lm dtherm kaiser
bugs	: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 3990.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model	: 23
model name	: Intel(R) Core(TM)2 Duo CPU P7350 @ 2.00GHz
stepping	: 6
microcode	: 0x60f
cpu MHz	: 800.000
cache size	: 3072 KB
physical id	: 0
siblings	: 2
core id	: 1
cpu cores	: 2
apicid	: 1
initial apicid	: 1
fpu	: yes
fpu_exception	: yes
cpuid level	: 10
wp	: yes
flags	: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm sse4_1 lahf_lm dtherm kaiser
bugs	: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 3990.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

**Comment by coldfix** [comment]
Copied from #42:

Hey, your exception shows that you're using python 3.4 with a udiskie version that requires 3.5+. I did not post an official release with this backward breakage so far, so I assume you either installed it manually from github or you should notify your package maintainer about the package being broken.

On which OS are you and what package manager did you use? Looks like you installed udiskie from github into a py3.4 environment, which is not supported. If you want py3.4 you will have to use an udiskie 1.7 version.

**Comment by ernie-cordell** [comment]
Opensuse Leap 42.3 -- fairly standard version.  It makes sense, my package installer always uses the latest available version.  The update was probably automatic.

**Comment by ernie-cordell** [comment]
And thanks for getting back to me so quickly.  So far I've only had to pay attention to whether my Python was  2 or 3.
