### ISSUE TITLE
UDISKS_IGNORE and loop mounts.

### ISSUE THREAD

**Issue by denisfa** [coldfix/udiskie#181]
Hey, 

I want to ask about a behaviour I found on `udiskie` (`1.7.7`) while using the following setup. My fstab has this line:
```
/opt/home-ext4.img  /mnt/ext4-home  auto  loop 0 0
```

I also have an udev rule like this:
```
SUBSYSTEM=="block", KERNEL=="loop*", ENV{UDISKS_IGNORE}="1"
```

If I unmount and then mount `/mnt/ext4-home`, I see this:
```
$ udevadm monitor --environment --udev

UDEV  [17013.331428] change   /devices/virtual/block/loop0 (block)
ACTION=change
DEVPATH=/devices/virtual/block/loop0
SUBSYSTEM=block
DEVNAME=/dev/loop0
DEVTYPE=disk
SEQNUM=3421
USEC_INITIALIZED=4435897
UDISKS_IGNORE=1
ID_FS_LABEL=Dropbox
ID_FS_LABEL_ENC=Dropbox
ID_FS_UUID=e9c8aee0-960b-48a5-ab10-301f69605778
ID_FS_UUID_ENC=e9c8aee0-960b-48a5-ab10-301f69605778
ID_FS_VERSION=1.0
ID_FS_TYPE=ext4
ID_FS_USAGE=filesystem
.ID_FS_TYPE_NEW=ext4
MAJOR=7
MINOR=0
DEVLINKS=/dev/disk/by-label/Dropbox /dev/disk/by-uuid/e9c8aee0-960b-48a5-ab10-301f69605778
TAGS=:systemd:
```

`udiskie` still shows this loop device. I know I can get around with the config file:
```
$ cat .config/udiskie/config.yml 
# Do not show loop devices mounts.
device_config:
  - is_loop: true
    ignore: true
```

I wanted to confirm if the loop mounts should ignore the `UDISKS_IGNORE=1` property. I have set another udev rule to ignore RAID devices by using this variable and, therefore, no extra configuration for `udiskie` to ignore them.

**Comment by coldfix** [comment]
I have to apologize for ignoring this issue for so long.

The reason the device was shown is that udiskie has a builtin rule that says loop files should be shown, which is evaluated before the rule that says ignored devices should be hidden.

I have now adjusted this rule to show only non-ignored loop files. This change will be in the release (2.0.5) and should hide the device by default with your given udev rule.

In the meantime, if you're still using udiskie as of now, there are several ways to ignore your device. As you figured out, one way would be to ignore all loop devices by filtering for `is_loop: true`. Another option would be to use a filter `is_ignored: true` which if given in the config file is inserted before the builtin rules and should therefore also achieve the correct behaviour. Third option, is to only ignore specifically your device by matching against the `id_uuid` or `loop_file` properties.
