### ISSUE TITLE
[Feature request] Dynamic home path in config.yml

### ISSUE THREAD

**Issue by sheoak** [coldfix/udiskie#182]
I would like to include my keyfiles depending on the current home path but I couldn't find a way to do it without writing the username in the config.yml file. Would this be possible to implement "~/" or $HOME expand?

Now:
```
device_config:
- id_uuid: xxx-xxx-xxx
  keyfile: /home/username/keyfile
```

Wish:
```
device_config:
- id_uuid: xxx-xxx-xxx
  keyfile: ~/keyfile
```

or
```
device_config:
- id_uuid: xxx-xxx-xxx
  keyfile: $ENV_KEYFILE_PATH/keyfile
```

I can have a try if you give me some instruction to code it well.
Cheers!

**Comment by coldfix** [comment]
Sure, should be easy, I will include it in the next version, leave this open for now so I don't forget:)
