### ISSUE TITLE
Piping LUKS password into udiskie-mount

### ISSUE THREAD

**Issue by caelanritter** [coldfix/udiskie#183]
I've checked the wiki and man page, but I can't seem to figure out how to pipe a password directly into `udiskie-mount`; more specifically, I'm trying to do something along the lines of `echo "mypassword" | udiskie-mount /dev/sda1`, but it completely ignores the input (whether correct or incorrect) and instead prompts me to enter the password with a desktop popup.  (For reference, running `udiskie-mount /dev/sda1` alone prompts me from the terminal rather than a popup: `Enter password for /dev/sda1:`.)

**Comment by coldfix** [comment]
Hi, piping is so far not directly possible. However, you could do something like

```
udiskie-mount /dev/sda1 -p 'echo "mypassword"'

# or

udiskie-mount /dev/sda1 -p 'cat /my/passkey'
```

**Comment by caelanritter** [comment]
Thanks for the response.  So, I tried this (although I figured I was using the `-p` option incorrectly; it might be helpful to add those uses you mentioned to the wiki/man page). What I'm actually trying to do is use `pass keyfile`, which decrypts `keyfile.gpg` and outputs the contents.  So, for example,
```
pass keyfile | sudo cryptsetup --key-file=- open /dev/sda1 myvault
```
works as expected, but when I run
```
udiskie-mount /dev/sda1 -p 'pass keyfile'
```
I get
```
failed to unlock /org/freedesktop/UDisks2/block_devices/sda1: Invalid UTF-8 in child stdout at offset 93909913255506
```
I can only gather that this means that `udisks2` doesn't like `keyfile`, which is a binary file.  Is there any way around this, or will it only work with text files?

**Comment by coldfix** [comment]
> ```
> 
> ```
> 
> 
> I get
> 
> ```
> failed to unlock /org/freedesktop/UDisks2/block_devices/sda1: Invalid UTF-8 in child stdout at offset 93909913255506
> ```

I think this should be fixable by replacing usage of  `Gio.Subprocess.communicate_utf8_async` with [`communicate_async`](https://lazka.github.io/pgi-docs/Gio-2.0/classes/Subprocess.html#Gio.Subprocess.communicate_async) in `udiskie.async_.exec_subprocess`. But there is something that lingers in the back of my head that was related to usage of these two functions, I will have to investigate some more first.

**Comment by coldfix** [comment]
Hi, somehow I've forgotten about this for the last 6 months. FYI udiskie 2.0.4 that should allow using `-p` with commands that return binary data.

**Comment by coldfix** [comment]
Please give me a note if this is still an issue, and I will reopen.
