### ISSUE TITLE
Disks are not mounted anymore

### ISSUE THREAD

**Issue by mb720** [coldfix/udiskie#192]
Hi and thanks a lot for udiskie!

After upgrading to udiskie 2.0.1, the automount feature doesn't work anymore.

Specifically, when udiskie is running and I plug in an external drive, the external drive is not mounted at `/run/media/me/`.

On the other hand, having a drive plugged in *and then* starting udiskie works fine: the drive is mounted.

Here's the output of `udiskie --no-notify -v` with a drive plugged in (the last lines correctly state that the drive is mounted):

    DEBUG [2019-12-30 11:34:38,553] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/me/.config/udiskie/config.yml'
    DEBUG [2019-12-30 11:34:38,556] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/me/.config/udiskie/config.json'
    DEBUG [2019-12-30 11:34:38,566] udiskie.udisks2: Daemon version: 2.8.4
    DEBUG [2019-12-30 11:34:38,566] udiskie.udisks2: Keyfile support: True
    DEBUG [2019-12-30 11:34:38,684] udiskie.config: IgnoreDevice(match={'symlinks': '/dev/mapper/docker-*'}, value={'ignore': True}) created
    DEBUG [2019-12-30 11:34:38,684] udiskie.config: IgnoreDevice(match={'symlinks': '/dev/disk/by-id/dm-name-docker-*'}, value={'ignore': True}) created
    DEBUG [2019-12-30 11:34:38,685] udiskie.config: IgnoreDevice(match={'is_loop': True, 'loop_file': '/*'}, value={'ignore': False}) created
    DEBUG [2019-12-30 11:34:38,685] udiskie.config: IgnoreDevice(match={'is_block': False}, value={'ignore': True}) created
    DEBUG [2019-12-30 11:34:38,685] udiskie.config: IgnoreDevice(match={'is_external': False}, value={'ignore': True}) created
    DEBUG [2019-12-30 11:34:38,685] udiskie.config: IgnoreDevice(match={'is_ignored': True}, value={'ignore': True}) created
    DEBUG [2019-12-30 11:34:38,723] udiskie.config: IgnoreDevice(match={'is_block': False}, ignore=True) used for /org/freedesktop/UDisks2/drives/INTEL_SSDSA2BW160G3L_CVPR1451090D160DGN
    DEBUG [2019-12-30 11:34:38,724] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/sda3
    DEBUG [2019-12-30 11:34:38,724] udiskie.config: IgnoreDevice(match={'is_block': False}, ignore=True) used for /org/freedesktop/UDisks2/drives/Intenso_External_USB_3_2e0_2012071315260
    DEBUG [2019-12-30 11:34:38,724] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/sda1
    DEBUG [2019-12-30 11:34:38,724] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/sda
    DEBUG [2019-12-30 11:34:38,728] udiskie.mount: mounting /org/freedesktop/UDisks2/block_devices/sdb1 with {'options': None}
    DEBUG [2019-12-30 11:34:40,103] udiskie.udisks2: +++ device_changed: /org/freedesktop/UDisks2/block_devices/sdb1
    DEBUG [2019-12-30 11:34:40,104] udiskie.udisks2: +++ device_mounted: /org/freedesktop/UDisks2/block_devices/sdb1
    mounted /org/freedesktop/UDisks2/block_devices/sdb1 on /run/media/me/TWINNI
    INFO [2019-12-30 11:34:40,104] udiskie.mount: mounted /org/freedesktop/UDisks2/block_devices/sdb1 on /run/media/me/TWINNI
    DEBUG [2019-12-30 11:34:40,112] udiskie.udisks2: +++ device_changed: /org/freedesktop/UDisks2/block_devices/sdb1

Here's the output of `udiskie --no-notify -v` where initially no drive is connected. The drive is connected at 11:38:41 which udiskie registers, but it doesn't mount the drive:

    DEBUG [2019-12-30 11:38:29,640] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/me/.config/udiskie/config.yml'
    DEBUG [2019-12-30 11:38:29,643] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/me/.config/udiskie/config.json'
    DEBUG [2019-12-30 11:38:29,650] udiskie.udisks2: Daemon version: 2.8.4
    DEBUG [2019-12-30 11:38:29,651] udiskie.udisks2: Keyfile support: True
    DEBUG [2019-12-30 11:38:29,746] udiskie.config: IgnoreDevice(match={'symlinks': '/dev/mapper/docker-*'}, value={'ignore': True}) created
    DEBUG [2019-12-30 11:38:29,746] udiskie.config: IgnoreDevice(match={'symlinks': '/dev/disk/by-id/dm-name-docker-*'}, value={'ignore': True}) created
    DEBUG [2019-12-30 11:38:29,746] udiskie.config: IgnoreDevice(match={'is_loop': True, 'loop_file': '/*'}, value={'ignore': False}) created
    DEBUG [2019-12-30 11:38:29,746] udiskie.config: IgnoreDevice(match={'is_block': False}, value={'ignore': True}) created
    DEBUG [2019-12-30 11:38:29,746] udiskie.config: IgnoreDevice(match={'is_external': False}, value={'ignore': True}) created
    DEBUG [2019-12-30 11:38:29,746] udiskie.config: IgnoreDevice(match={'is_ignored': True}, value={'ignore': True}) created
    DEBUG [2019-12-30 11:38:29,781] udiskie.config: IgnoreDevice(match={'is_block': False}, ignore=True) used for /org/freedesktop/UDisks2/drives/INTEL_SSDSA2BW160G3L_CVPR1451090D160DGN
    DEBUG [2019-12-30 11:38:29,781] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/sda3
    DEBUG [2019-12-30 11:38:29,782] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/sda1
    DEBUG [2019-12-30 11:38:29,782] udiskie.config: IgnoreDevice(match={'is_external': False}, ignore=True) used for /org/freedesktop/UDisks2/block_devices/sda

    // The device is plugged in now

    DEBUG [2019-12-30 11:38:41,017] udiskie.udisks2: +++ device_added: /org/freedesktop/UDisks2/drives/Intenso_External_USB_3_2e0_2012071315260
    DEBUG [2019-12-30 11:38:41,021] udiskie.udisks2: +++ device_added: /org/freedesktop/UDisks2/block_devices/sdb
    DEBUG [2019-12-30 11:38:41,187] udiskie.udisks2: +++ device_added: /org/freedesktop/UDisks2/block_devices/sdb1
    DEBUG [2019-12-30 11:38:41,187] udiskie.udisks2: +++ device_changed: /org/freedesktop/UDisks2/block_devices/sdb

Has the usage of udiskie changed in 2.0.1? How do I get automount working as before? Thanks!

**Comment by coldfix** [comment]
Hi and many thanks for reporting! I will try to investigate this in more detail in the next days. Might be related to #191.

**Comment by coldfix** [comment]
Hey, thanks again, it was a pretty dumb mistage on my end. Released a new version. In case of further problems, feedback is always appreciated! and Happy new year

**Comment by mb720** [comment]
Thanks for looking into this!
Same to you :-)

**Comment by mb720** [comment]
Great job on fixing this! I can confirm that automounting works with udiskie 2.0.2 on Arch Linux. 👍
