### ISSUE TITLE
daemon not automounting usb drive anymore

### ISSUE THREAD

**Issue by NWuensche** [coldfix/udiskie#194]
Hello everybody,

I always used udiskie for automounting all usb-drives. I open the daemon by `exec /usr/bin/udiskie &` in my `.config/i3/config` file. 

However, since the last update, this doesn't work anymore. When pluging in a usb drive, I get the usual notification "Device added - device appered on /dev/sdb" , but I don't get the usual "Device mounted" notification. Also, the usb drive doesn't get mounted. 
The only way to mount the usb drive is to plug in the usb drive first and then to execute `udiskie` again in the terminal. It does not work if the daemon is open *before* I plug in the usb drive. However, this always worked before.

I use Arch Linux and udiskie 2.0.1.

**Comment by coldfix** [comment]
Hi, sorry for your troubles. This is probably the same issue as #192, which is fixed in 2.0.2.

**Comment by NWuensche** [comment]
Thank you, #192 seems like the same problem I have. Sorry for the
duplicate.
