### ISSUE TITLE
mounting a drive with udiskie to a specific user or path

### ISSUE THREAD

**Issue by pacharanero** [coldfix/udiskie#195]
Hi, apologies if this isn't the correct place to be asking, but I'm trying to solve a problem on a [FreedomBox](https://www.freedombox.org/) (a local multipurpose utility and file server distribution, created by the Debian folks) running on a Raspberry Pi 3 within my home network. Freedombox uses `udiskie` running as part of a service, to automount removable drives.

Unfortunately, because `udiskie` is running as the root user, it mounts them all at `/media/root/<DEVICE_NAME>`, meaning that the user running the FreedomBox services cannot access them. In particular this is causing difficulty in using external drives for backups using Syncthing.

The issue is described in these posts on the FreedomBox forum, which is where I found out about the use of `udiskie`.

https://discuss.freedombox.org/t/adding-usb-hdd-to-a-freedombox/601
https://discuss.freedombox.org/t/adding-external-usb-hdd-to-a-freedombox/613/3

But unfortunately this has led to a dead end. I was hoping to be able to configure `udiskie` (which is running as root) to mount the inserted drives at a different location, ideally one that the FreedomBox user can access. (Or alternatively, with different permissions). From the `udiskie` manpages and documentation I couldn't immediately see how to do this.

**Comment by coldfix** [comment]
Hi,

sorry for the late reply. Mount paths are not configurable, the only thing you can do is to request `/media/<device-name>` to be used as device name, see https://github.com/coldfix/udiskie/wiki/Custom-mount-paths.

Note that udiskie is not meant to be run as root user and can be started as normal user. udiskie is merely a client for udisks2 which runs in the background as root and uses polkit to figure out which user is allowed to do what.

**Comment by pacharanero** [comment]
Thanks @coldfix 
I suspect the solution here is to stop udiskie being run at startup by the root user, and instead start it as the correct user so that (for my user and a disk called `backups`) the default mount-point will be `/media/marcus/backup` - which will be accessible.

**Comment by coldfix** [comment]
I agree, running as the correct user would be preferrable. As noted on the wiki (see reference above), there is also the possibility to force `/media/<devicename>` for all users, but this would also require creating a customization, so I'm not sure it is suitable for you.
