### ISSUE TITLE
Can't mount drives with udiskie

### ISSUE THREAD

**Issue by deadpyxel** [coldfix/udiskie#200]
I just installed udiskie and followed the initial setup.

I created the `50-udiskie.rules`  with 644 permissions as the documentation suggested, and added `udiskie` to my ~/.xinitrc:
```
udiskie &
xbindkeys
exec i3
```

Even after many reboots, I can't get `udiskie` to mount anything, neither my Windows partition (That mounts fine using `udiskctl mount -b /dev/sda4`) or my external hdd (That can't mount even with `udiskctl`

Not sure what I'm doing wrong, but I guess is some misconffiguration. Are there any step I can do to get some debugging info.

For the record, if I run `udiskie` on terminal, no errors are shown.

I'm using Archlinux with kernel `5.5.6-arch1-1` as of now, with udiskie version 2.1.0.

**Comment by coldfix** [comment]
Hi,

thanks for trying udiskie. A first step in identifying the problem would be to look at the output of `udisksctl dump` to check which devices are recognized by udisks.

For the windows partition, since I guess it is internal, the default rules in udiskie will exclude it from being handled. To mitigate this, add an entry like this in your `~/.config/udiskie/config.yml`:

```yaml
device_config:
  - device_file: /dev/sda4
    ignore: false
```

As for the other partition. If it turns out that it is not handled by udisks, there is no chance that udiskie will. Does it have any special filesystem/raid/encryption/...? How do you mount it using `mount`?

**Comment by deadpyxel** [comment]
Thanks for the swift reply. As for now, to mount the external HDD (sdb) I am running:
```
sudo mount -t ntfs /dev/sdb1 /mnt/external
```
The Hard drive mounts fine, but udisks throws this error if I try to mount it using `udiskctl mount -b /dev/sdb1`:
```
Object /org/freedesktop/UDisks2/block_devices/sdb1 is not a mountable filesystem.
```

It is a simple External NTFS formatted drive I use to store personal files. nothing special. I'll test the configuration you talked about and update if that fix it.

**Comment by deadpyxel** [comment]
Thanks for the swift reply. As for now, to mount the external HDD (sdb) I am running:
```
sudo mount -t ntfs /dev/sdb1 /mnt/external
```
The Hard drive mounts fine, but udisks throws this error if I try to mount it using `udiskctl mount -b /dev/sdb1`:
```
Object /org/freedesktop/UDisks2/block_devices/sdb1 is not a mountable filesystem.
```

It is a simple External NTFS formatted drive I use to store personal files. nothing special. I'll test the configuration you talked about and update if that fix it.

**Comment by deadpyxel** [comment]
**Update:** I've tried the steps aforementioned, and udiskie can't mount the internal partition. Attempting `udiskie-mount /dev/sda4` throws this error:
```
failed to mount /org/freedesktop/UDisks2/block_devices/sda4: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorizedCanObtain: Not authorized to perform operation
```

While `udiskctl mount -b /dev/sda4` mounts it fine after inputing password. My guess is some misconfiguration on polkit, so here is the config file:
```
polkit.addRule(function(action, subject) {
  var YES = polkit.Result.YES;
  // NOTE: there must be a comma at the end of each line except for the last:
  var permission = {
    // required for udisks1:
    "org.freedesktop.udisks.filesystem-mount": YES,
    "org.freedesktop.udisks.luks-unlock": YES,
    "org.freedesktop.udisks.drive-eject": YES,
    "org.freedesktop.udisks.drive-detach": YES,
    // required for udisks2:
    "org.freedesktop.udisks2.filesystem-mount": YES,
    "org.freedesktop.udisks2.encrypted-unlock": YES,
    "org.freedesktop.udisks2.eject-media": YES,
    "org.freedesktop.udisks2.power-off-drive": YES,
    // required for udisks2 if using udiskie from another seat (e.g. systemd):
    "org.freedesktop.udisks2.filesystem-mount-other-seat": YES,
    "org.freedesktop.udisks2.filesystem-unmount-others": YES,
    "org.freedesktop.udisks2.encrypted-unlock-other-seat": YES,
    "org.freedesktop.udisks2.eject-media-other-seat": YES,
    "org.freedesktop.udisks2.power-off-drive-other-seat": YES
  };
  if (subject.isInGroup("storage")) {
    return permission[action.id];
  }
});
```

About the external hard drive, udisks says it is not a mountable file system, so I am guessing there's some problem with the partition table of sort (still mount can handle it fine).

**Comment by coldfix** [comment]
Hi,

right, for internal devices, you also need the `org.freedesktop.udisks2.filesystem-mount-system` permission. For a full list of actions, type `pkaction | grep udisks2`, or look [here](http://storaged.org/doc/udisks2-api/latest/udisks-polkit-actions.html).

The external drive is curious. You should probably report this over at [udisks](https://github.com/storaged-project/udisks/issues). Can you show the output of `udisksctl dump`, specifically the entries for `/dev/sdb*`?

Best, Thomas

**Comment by deadpyxel** [comment]
Sure. This is the output for `udisksctl dump | grep sdb`
```
/org/freedesktop/UDisks2/block_devices/sdb:
    Device:                     /dev/sdb
    PreferredDevice:            /dev/sdb
    Partitions:         ['/org/freedesktop/UDisks2/block_devices/sdb1']
/org/freedesktop/UDisks2/block_devices/sdb1:
    Device:                     /dev/sdb1
    PreferredDevice:            /dev/sdb1
    Table:              '/org/freedesktop/UDisks2/block_devices/sdb'
```

**Comment by coldfix** [comment]
Show it ungrepped please, there is more useful information on adjacent lines.

**Comment by deadpyxel** [comment]
Sorry about that:
```
/org/freedesktop/UDisks2/block_devices/sdb:
  org.freedesktop.UDisks2.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/sdb
    DeviceNumber:               2064
    Drive:                      '/org/freedesktop/UDisks2/drives/Samsung_M3_Portable_00000000011E4325'
    HintAuto:                   true
    HintIconName:               
    HintIgnore:                 false
    HintName:                   
    HintPartitionable:          true
    HintSymbolicIconName:       
    HintSystem:                 false
    Id:                         by-id-usb-Samsung_M3_Portable_00000000011E4325-0:0
    IdLabel:                    
    IdType:                     
    IdUUID:                     
    IdUsage:                    
    IdVersion:                  
    MDRaid:                     '/'
    MDRaidMember:               '/'
    PreferredDevice:            /dev/sdb
    ReadOnly:                   false
    Size:                       1000194400256
    Symlinks:                   /dev/disk/by-id/usb-Samsung_M3_Portable_00000000011E4325-0:0
                                /dev/disk/by-path/pci-0000:00:14.0-usb-0:1:1.0-scsi-0:0:0:0
    UserspaceMountOptions:      
  org.freedesktop.UDisks2.PartitionTable:
    Partitions:         ['/org/freedesktop/UDisks2/block_devices/sdb1']
    Type:               dos
/org/freedesktop/UDisks2/block_devices/sdb1:
  org.freedesktop.UDisks2.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/sdb1
    DeviceNumber:               2065
    Drive:                      '/org/freedesktop/UDisks2/drives/Samsung_M3_Portable_00000000011E4325'
    HintAuto:                   true
    HintIconName:               
    HintIgnore:                 false
    HintName:                   
    HintPartitionable:          true
    HintSymbolicIconName:       
    HintSystem:                 false
    Id:                         by-id-usb-Samsung_M3_Portable_00000000011E4325-0:0-part1
    IdLabel:                    
    IdType:                     
    IdUUID:                     
    IdUsage:                    
    IdVersion:                  
    MDRaid:                     '/'
    MDRaidMember:               '/'
    PreferredDevice:            /dev/sdb1
    ReadOnly:                   false
    Size:                       1000192606208
    Symlinks:                   /dev/disk/by-id/usb-Samsung_M3_Portable_00000000011E4325-0:0-part1
                                /dev/disk/by-path/pci-0000:00:14.0-usb-0:1:1.0-scsi-0:0:0:0-part1
    UserspaceMountOptions:      
  org.freedesktop.UDisks2.Partition:
    Flags:              0
    IsContained:        false
    IsContainer:        false
    Name:               
    Number:             1
    Offset:             1048576
    Size:               1000192606208
    Table:              '/org/freedesktop/UDisks2/block_devices/sdb'
    Type:
    UUID:
```
These are all lines related to the `sdb`
As a note, here is what the dump says about the external hard drive:
```
/org/freedesktop/UDisks2/drives/Samsung_M3_Portable_00000000011E4325:
  org.freedesktop.UDisks2.Drive:
    CanPowerOff:                true
    Configuration:              {}
    ConnectionBus:              usb
    Ejectable:                  false
    Id:                         Samsung-M3-Portable-00000000011E4325
    Media:                      
    MediaAvailable:             true
    MediaChangeDetected:        true
    MediaCompatibility:         
    MediaRemovable:             false
    Model:                      M3 Portable
    Optical:                    false
    OpticalBlank:               false
    OpticalNumAudioTracks:      0
    OpticalNumDataTracks:       0
    OpticalNumSessions:         0
    OpticalNumTracks:           0
    Removable:                  true
    Revision:                   3
    RotationRate:               -1
    Seat:                       seat0
    Serial:                     00000000011E4325
    SiblingId:                  /sys/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0
    Size:                       1000194400256
    SortKey:                    00coldplug/12removable/sd____b
    TimeDetected:               1582933248244336
    TimeMediaDetected:          1582933248244336
    Vendor:                     Samsung
    WWN:
```

**Comment by coldfix** [comment]
Hey,

thanks! Unfortunately, I don't really see anything particularly interesting here, except that of course the `org.freedesktop.UDisks2.Filesystem` interface is missing from the device, as was indicated by the error messages.

I would guess it is some kind of problem with how the device was formatted or partitioned, but I'm not the right person to debug this kind of issue. I would ask the people over at udisks for more advice.

Best, Thomas
