### ISSUE TITLE
Couldn't generate custom notifications

### ISSUE THREAD

**Issue by mushi-nova** [coldfix/udiskie#208]
It's an awesome application but I was trying to generate custom notifications for different events such as `mount` and `unmount`. Is there any possible way to do so?

I tried to generate custom notification using `--notify-command` but it was of no avail at all. I would really appreciate if you can guide me with it.

**Comment by coldfix** [comment]
Hi,

what did you try so far?

It should work by passing `--notify-command COMMAND` on the command line when starting the udiskie daemon. An example with zenity is given in the manual, here an even simpler one:

```
udiskie --notify-command "echo {event} {device_presentation}"
```

In case of problems, please let me know what behaviour you observe.

**Comment by Geeky-nutcracker** [comment]
Thanks for your quick reply. Really appreciate it. Going back to my issue, my notifications are displayed perfectly which is the default ones. But I wish to include **custom icons** for **different events** such as `mount` or `eject`. I did try the following 
`udiskie --notify-command "notify-send --icon=<icon_location> {event} {device_presentation}"`
But I couldn't make it work like that.

**Comment by coldfix** [comment]
> But I couldn't make it work like that.

please let me know what behaviour you observe.

Does it show a notification or none at all? Does my above example command behave as expected?

Note that you must pass the absolute path of the icon to `notify-send`.

**Comment by Mushinova** [comment]
I used the following command `udiskie --notify-command "notify-send --icon=$HOME/.config/udiskie {event} {device_presentation}"` and it is properly showing the icon but I was trying to show separate notifications along with separate icons for `mount` and `unmount` of the external device. So what could be the possible way to achieve that or is there a possibility of achieving that?

**Comment by coldfix** [comment]
> and it is properly showing the icon

So, everything works...?

> but I was trying to show separate notifications along with separate icons for mount and unmount of the external device. So what could be the possible way to achieve that or is there a possibility of achieving that?

Should be easy enough to figure out the rest on your own...
