### ISSUE TITLE
Notification button on multi-partition drive mounts wrong partition

### ISSUE THREAD

**Issue by patrick96** [coldfix/udiskie#217]
I have a two-partition USB stick and when inserting it and clicking on the left button in the notification created by udiskie, udiskie mounts the partition tied to the second button:

![2021-03-01-180355_432x127_scrot](https://user-images.githubusercontent.com/2452038/109531934-d3becc80-7ab8-11eb-9c1c-d0bb29bcad71.png)

And after I click the button on the left for `/dev/sdg1`, it tells me that `/dev/sdg2` was mounted (and it was):

![2021-03-01-180404_451x123_scrot](https://user-images.githubusercontent.com/2452038/109531931-d3becc80-7ab8-11eb-8ee9-d02d33e6b4c9.png)

## Investigation

I tried digging into the code and fixing it, but I was unable to. Here is what I found out:

The callback registered in `Notify._add_action` seems to be correct (the device object bound to the `Mounter.mount` is the one for `/dev/sdg1`). However, the device passed for `Mounter.mount` is now the one for `/dev/sdg2`.

I wasn't able to figure out where in between things went wrong because the execution is non-linear and I didn't really understand the program flow through `async_.py`.

It seems that for some reason the wrong callback is selected.

## Setup

I am running udiskie 2.3.2, but was also able to reproduce this on the newest commit 3ff94d2a953ad915bec1d3eb47076f7f622a4294

The notification daemon is [`xfce4-notifyd` 0.6.2](https://docs.xfce.org/apps/notifyd/start), though the same happens with [`notification-daemon` 3.20.0](https://github.com/GNOME/notification-daemon).

On my system version 0.7.9 of `libnotify` is installed

I started udiskie with the following command:

```
udiskie -A --no-tray --notify
```

And finally this is the partition table printed by `fdisk` for the drive (if that is even relevant):

```
Disk /dev/sdg: 7.33 GiB, 7866580992 bytes, 15364416 sectors
Disk model: DataTraveler 3.0
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: DA0E6645-62BE-6149-82AD-153BF7A2791F

Device       Start      End Sectors  Size Type
/dev/sdg1     2048  8390655 8388608    4G Linux filesystem
/dev/sdg2  8390656 15364382 6973727  3.3G Linux filesystem
```

Let me know if you need any more information.

**Comment by coldfix** [comment]
Hi,

many thanks for reporting the issue.

I have identified the problem (both actions pass the same "action id" no the notify API and will therefore override each other) and will fix it for the next version.

Sorry for the inconvenience.

Thomas

**Comment by patrick96** [comment]
Awesome! Thanks for the fast response :smiley: 

I can confirm it works now with the newest commit.

**Comment by coldfix** [comment]
Great! Just now released the fix for the next version.
