### ISSUE TITLE
Tray icon

### ISSUE THREAD

**Issue by joaopauloalbq** [coldfix/udiskie#225]
The tray icon is colorful when it should be monochrome.

![Screenshot_20210705_161845](https://user-images.githubusercontent.com/9905202/124521155-ed548580-ddc4-11eb-96ff-205d207a54da.png)

When the panel is very small it is using the correct icon.

![Screenshot_20210705_172859](https://user-images.githubusercontent.com/9905202/124521163-f80f1a80-ddc4-11eb-9784-e648e55d48be.png)

**Comment by coldfix** [comment]
Hi,

that might mean that none of the icons that udiskie tries by default can be found in the requested theme.

You can configure udiskie manually to show a different icon by putting a list of icon names in your `~/.config/udiskie/config.yml`:

```yaml
icon_names:
  media: [media-optical]
```

where the name refers to one of the icons in your `/usr/share/icons/[theme]` directory. The default list that udiskie will try is 

```yml
icon_names: [
            'drive-removable-media-usb-pendrive',
            'drive-removable-media-usb',
            'drive-removable-media',
            'media-optical',
            'media-flash',
]
```

Let me know, if you find another icon name that should be added to the list.

**Comment by joaopauloalbq** [comment]
My icon theme (Papirus) is purposely showing a 22x22 colored _media_ icon. 

Had to change to another monochrome icon.

`device` was the best option that I found. `media-eject` is also cool but it's redundant

Thank you for this wonderful personalization :D

![udiskie](https://user-images.githubusercontent.com/9905202/124686738-01be7e00-deaa-11eb-86d3-93224715ae27.png)

**Comment by joaopauloalbq** [comment]
Papirus Team added a monochrome icon to be used correctly on the panel called `drive-removable-media-usb-panel`, could you add to the list?

Best regards!

**Comment by varlesh** [comment]
only one note this file must be first in the list, otherwise it won't work

**Comment by coldfix** [comment]
Sure, thanks for the info!

**Comment by raffaem** [comment]
> Hi,
> 
> that might mean that none of the icons that udiskie tries by default can be found in the requested theme.
> 
> You can configure udiskie manually to show a different icon by putting a list of icon names in your `~/.config/udiskie/config.yml`:
> 
> ```yaml
> icon_names:
>   media: [media-optical]
> ```
> 
> where the name refers to one of the icons in your `/usr/share/icons/[theme]` directory. The default list that udiskie will try is
> 
> ```yaml
> icon_names: [
>             'drive-removable-media-usb-pendrive',
>             'drive-removable-media-usb',
>             'drive-removable-media',
>             'media-optical',
>             'media-flash',
> ]
> ```
> 
> Let me know, if you find another icon name that should be added to the list.

Why in the first code snippet there is a `media` suboption and in the second there isn't?

**Comment by raffaem** [comment]
I have put:
```
icon_names:
  # Customize the icon set used by the tray widget. Each entry
  # specifies a list of icon names. The first installed icon from
  # that list will be used.
  media:   [drive-removable-media-usb-panel]
```
in my config file (I have `/usr/share/icons/Papirus/24x24/panel/drive-removable-media-usb-panel`), but udiskie seems unable to find it. It shows a red cross on the tray icon.

Where does udiskie search for tray icons, and how can I customize this path?

**Comment by raffaem** [comment]
ok fixed it.

Set `config="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"`.

Open `$config` and set `gtk-icon-theme-name` under `[Settings]` header. Example:
```
[Settings]
gtk-icon-theme-name=Papirus
```

Run this script to import the settings ([reference](https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland#setting-values-in-gsettings)):

```
#!/bin/sh

# usage: import-gsettings
config="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
if [ ! -f "$config" ]; then exit 1; fi

gnome_schema="org.gnome.desktop.interface"
gtk_theme="$(grep 'gtk-theme-name' "$config" | sed 's/.*\s*=\s*//')"
icon_theme="$(grep 'gtk-icon-theme-name' "$config" | sed 's/.*\s*=\s*//')"
cursor_theme="$(grep 'gtk-cursor-theme-name' "$config" | sed 's/.*\s*=\s*//')"
font_name="$(grep 'gtk-font-name' "$config" | sed 's/.*\s*=\s*//')"
gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
gsettings set "$gnome_schema" icon-theme "$icon_theme"
gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
gsettings set "$gnome_schema" font-name "$font_name"
```

**Comment by raffaem** [comment]
For reference, the script I use to start udiskie (something is changing the GTK3 settings, I guess it's the Plasma session):

```
#!/usr/bin/env bash
sed -E -i.bak 's/^(gtk-icon-theme-name=).*$/\1Papirus/g' ~/.config/gtk-3.0/settings.ini
import_gsettings
killall udiskie
udiskie &
disown
```
