### ISSUE TITLE
Open file manager by click on notification

### ISSUE THREAD

**Issue by timsofteng** [coldfix/udiskie#233]
Hello.
I'm using `mako` as my notification demon. I works good with `udiskie` except of one feature.
I want to open my file-manager by click on success mount notification.
Should I configure anything or it works by default?
Now it doesn't work for me. However when i click `Browse /dev/sdb: 'some-name'` in tray indicator it works.

**Comment by coldfix** [comment]
If the notification daemon supports it, there should normally be a button for this in the notification (similar to the one shown [here](https://raw.githubusercontent.com/coldfix/udiskie/master/screenshot.png) in the background on the right). From the minimalistic looks of it, mako might not support this feature.

**Comment by timsofteng** [comment]
> If the notification daemon supports it, there should normally be a button for this in the notification (similar to the one shown [here](https://raw.githubusercontent.com/coldfix/udiskie/master/screenshot.png) in the background on the right). From the minimalistic looks of it, mako might not support this feature.

It's interesting.
I guessed mako supports actions (according to its documentation).

**Comment by coldfix** [comment]
I suggest testing it by executing this simple python script:


```python
from gi import require_version
require_version('GLib', '2.0')
require_version('Notify', '0.7')

from gi.repository import GLib
from gi.repository import Notify

Notify.init('udiskie')

notification = Notify.Notification.new("title", "message", None)
notification.set_timeout(5000)
notification.add_action("action-one", "One", lambda *_: print("activated: One"))
notification.add_action("action-two", "Two", lambda *_: print("activated: Two"))
notification.show()

mainloop = GLib.MainLoop()
mainloop.run()
```

It should show a notification with two buttons. Let me know if it works.

**Comment by timsofteng** [comment]
@coldfix 
Here is what I can see:
![image](https://user-images.githubusercontent.com/51912173/147762395-60a4e34a-16ac-4ef1-8a11-8fb1b5101511.png)

**Comment by coldfix** [comment]
Ok, in that case it seems to be your notification daemon that doesn't support actions (or may need to be configured for it?). It should look something like this:

![notification](https://user-images.githubusercontent.com/1816880/147794105-9abd534c-af41-4e9c-958a-10b4233ead72.png)

I'm happy with xfce4-notifyd - but that's on X11, not sure it works for you.

Closing this for now. Let me know if the same problem persists with other notification daemon.
