### ISSUE TITLE
Unable to automount internal device

### ISSUE THREAD

**Issue by Subsentient** [coldfix/udiskie#235]
It appears that either the config.yml file is ignored or overridden by hardcoded values in udiskie, or YAML is just such an abhorrent config language that I can't figure out how to please it.
I need an internal drive, /dev/sda, to automount, and it appears that udiskie really, really, really doesn't want to allow me to do that.

Why?

**Comment by Subsentient** [comment]
It appears the latter hypothesis is correct, my apologies. Indentation in YAML is apparently not consistent. Can you add an example that works for JSON perhaps? I would have preferred that, but couldn't figure out just how it wanted the YAML values translated.

Thanks.

**Comment by coldfix** [comment]
Hi,

> Indentation in YAML is apparently not consistent.

Not sure what you mean. It does require consistent use of spacing. However, the spacing of the example in the man page is a bit hard to read, in particular because it is already indented due to the man page formatting. If that was your issue, maybe I should convert it to 4 space indentation, or better provide an external example file?

> Can you add an example that works for JSON perhaps?

For what specifically?

> (I cannot adequately express my displeasure on my first exposure to YAML >.<)

sorry for your bad experience with the file format.

**Comment by Subsentient** [comment]
Thank you for responding. I appreciate the work you've done here with udiskie very much.
Ideally it would be an example for JSON that's as comprehensive as the YAML one, but I'm not sure I should reasonably expect that -- it's a lot of work.

Things like automounting, disabling ignore, matching by GUID, etc would be helpful. Enough so I have an idea of how to handle the (very vaguely) nested blocks of YAML, but with JSON.
Thanks!

**Comment by coldfix** [comment]
Hi,

it's not a lot of work to convert. In fact I copy-pasted the yaml example from the man page into it's own file which you can download from [here](https://raw.githubusercontent.com/coldfix/udiskie/master/example/config.yml). It can be converted to json using this simple script:

```python
import json
import yaml

with open("config.yml") as f:
    data = yaml.safe_load(f)

with open("config.json", "wt") as f:
    json.dump(data, f, indent=4)
```

Giving this output:

```json
{
    "program_options": {
        "tray": "auto",
        "menu": "flat",
        "automount": false,
        "notify": true,
        "password_cache": 30,
        "file_manager": "xdg-open",
        "terminal": "termite -d",
        "password_prompt": [
            "gnome-keyring-query",
            "get",
            "{id_uuid}"
        ],
        "notify_command": "zenity --info --text '{event}: {device_presentation}'"
    },
    "device_config": [
        {
            "device_file": "/dev/dm-5",
            "ignore": false
        },
        {
            "id_uuid": "9d53-13ba",
            "options": [
                "noexec",
                "nodev"
            ],
            "ignore": false,
            "automount": false
        },
        {
            "id_type": "vfat",
            "ignore": true
        },
        {
            "id_type": "ntfs",
            "skip": true
        },
        {
            "ignore": true,
            "automount": false,
            "options": []
        }
    ],
    "mount_options": null,
    "ignore_device": null,
    "notifications": {
        "timeout": 1.5,
        "device_mounted": 5,
        "device_unmounted": false,
        "device_added": false,
        "device_removed": false,
        "device_unlocked": -1,
        "device_locked": -1,
        "job_failed": -1
    },
    "quickmenu_actions": [
        "mount",
        "unmount",
        "unlock",
        "terminal",
        "detach",
        "delete"
    ],
    "notification_actions": {
        "device_mounted": [
            "browse"
        ],
        "device_added": [
            "mount"
        ]
    },
    "icon_names": {
        "media": [
            "drive-removable-media",
            "media-optical"
        ],
        "browse": [
            "document-open",
            "folder-open"
        ],
        "terminal": [
            "terminal",
            "terminator",
            "xfce-terminal"
        ],
        "mount": [
            "udiskie-mount"
        ],
        "unmount": [
            "udiskie-unmount"
        ],
        "unlock": [
            "udiskie-unlock"
        ],
        "lock": [
            "udiskie-lock"
        ],
        "eject": [
            "udiskie-eject",
            "media-eject"
        ],
        "detach": [
            "udiskie-detach"
        ],
        "delete": [
            "udiskie-eject"
        ],
        "quit": [
            "application-exit"
        ]
    }
}
```

However, I'm hesitating to add this to the repo for now. One issue is that json doesn't allow comments for additional explanations.

**Comment by coldfix** [comment]
At some point I want to add more extensive online documentation where this might have a place, but I have no time for it at the moment.

**Comment by Subsentient** [comment]
@coldfix 
Thank you, that is exactly what I needed! Honestly that is probably sufficient to go into the readme itself, I don't think it even needs editing.
Thanks again!
