### ISSUE TITLE
Not authorized to mount on Linux Mint

### ISSUE THREAD

**Issue by joooeey** [coldfix/udiskie#258]
Udiskie automount doesn't work due to an authorization error. I've followed the guidance at [Permissions](https://github.com/coldfix/udiskie/wiki/Permissions) but that didn't help either.

```
~$ udiskie
failed to mount /org/freedesktop/UDisks2/block_devices/sdb1: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorized
nObtain: Not authorized to perform operation
```

The second line is printed when I plug in a flash drive.

**Comment by coldfix** [comment]
Hi,

1. is sdb1 an internal or external device? If internal (or falsely recognized as such), you may additionally need the `org.freedesktop.udisks2.filesystem-mount-system` permission.
You can check what udisks thinks about the device with:

```
udisksctl info -b /dev/sdb
```

2. Also, can you paste the exact content of your `.rules` file for the permissions?

3. Sometimes it helps to add another rule

```javascript
polkit.addRule(function(action, subject) {
  var prefix = "org.freedesktop.udisks";
  if (action.id.slice(0, prefix.length) == prefix)
    polkit.log(action.id);
});
```

and then, while trying to mount, monitor the output of:

```
journalctl -n 20 -f -u polkit.service
```
