### ISSUE TITLE
Why does the polkit rule grants permission to users in storage group?

### ISSUE THREAD

**Issue by madjxatw** [coldfix/udiskie#269]
I am using both Ubuntu and Fedora and neither of them has a `storage` group out of box. Doesn't it make more sense to consider `sudo` or `wheel` group?

**Comment by ProDeSquare** [comment]
Not sure but have you tried changing the group name from `storage` to `wheel` or `sudo` here?

```
if (subject.isInGroup("storage")) {
    return permission[action.id];
}
```

```
if (subject.isInGroup("wheel")) {
    return permission[action.id];
}
```

If this solves the issue mark this as an accepted answer

**Comment by coldfix** [comment]
The group "storage" is simply used as an example. You can replace it with whatever group you find more suitable, or create the group and add users to it with a single command. I'll state it a bit clearer in the wiki. I think using a preexisting group with a different purpose (such as sudo) isn't necessarily a good idea, as you may want users other than sudo users being able to mount devices for example.
