### ISSUE TITLE
Kobo Libra H2O e-reader does not get auto-mounted when connected via USB

### ISSUE THREAD

**Issue by fritzrehde** [coldfix/udiskie#274]
I have a [Kobo Libra H2O](https://us.kobobooks.com/products/kobo-libra-h2o). When plugging it into a USB port, the device is supposed to (this was the default behaviour on MacOS I experienced in the past) be auto-mounted to I can transfer ebook files. However, `udiskie` doesn't seem to recognize when I plug the Kobo device into the USB port. However, the Kobo's interface does show that it has detected the computer, and that it is connected. I can also see the device in `lsusb`'s output as `Kobo Inc. eReader-4.38.21908`.
Any help?

**Comment by coldfix** [comment]
Hi, can you check using `udisksctl` whether the device was found?


- `udisksctl dump` (snapshot, all devices)
- `udisksctl info -b /dev/sda1` (single device)
- `udisksctl monitor` (continuous monitoring)

**Comment by fritzrehde** [comment]
Unfortunately, I was unable to find the Kobo e-reader device when running `udisksctl monitor`. I find this quite strange, because the Kobo e-reader itself displays a screen that says it is "connected" (whatever that means) to the computer.

**Comment by fritzrehde** [comment]
Anything else I can do? For context, I remember enabling `LUKS` encryption when installing Arch Linux through the arch-install script a while back. Could that have some effect (probably not, just checking in case).

**Comment by coldfix** [comment]
Sorry, I'm not familiar with that device and don't know what interface it supports. Apparently it is not recognized as memory device by udisks. I'd speculate that it could be an MTP device. Can you mount it as [MTPfs](https://wiki.archlinux.org/title/Media_Transfer_Protocol#MTPfs)?

**Comment by fritzrehde** [comment]
Actually, I can see on the screen (I use [`koreader`](https://github.com/koreader/koreader)) that the e-reader device acts as a "USB Mass Storage" device. It says "USBMS session in progress. Please eject your device safely before unplugging it". Does this mean anything to you? I think this means it doesn't use MTP?

**Comment by fritzrehde** [comment]
Ok, quick update: After rebooting, I think thunar now seems to recognize it without any problems, and auto-mounts. I  read something about some kernel not being able to load new kernel modules (required for mounting usb drive) if the kernel was upgraded without a reboot. I should have tried the usual first, and only then asked: Reboot, and everything will be fine :) Thanks for the help. If thunar was able to auto-mount the drive, `udiskie` should be able to as well, right?

**Comment by coldfix** [comment]
> Ok, quick update: After rebooting, I think thunar now seems to recognize it without any problems, and auto-mounts. I read something about some kernel not being able to load new kernel modules (required for mounting usb drive) if the kernel was upgraded without a reboot. I should have tried the usual first, and only then asked: Reboot, and everything will be fine :) Thanks for the help.

Oh, yes, that's a common problem.

> If thunar was able to auto-mount the drive, `udiskie` should be able to as well, right?

Not necessarily.
