### ISSUE TITLE
Breaks in Python 3.12 due to dependency on distutils

### ISSUE THREAD

**Issue by philer** [coldfix/udiskie#278]
`distutils` from the standard library was deprecated in 3.10 ([PEP 632](https://peps.python.org/pep-0632/)) and removed in 3.12. It is still available on many systems as it is included with `setuptools` but if this is not installed, running `udiskie` yields the following error:  

**`ModuleNotFoundError: No module named 'distutils'`**

Full stack trace:
```
Traceback (most recent call last):
  File "/home/***/.local/bin/udiskie", line 5, in <module>
    from udiskie.cli import Daemon
  File "/home/***/.local/lib/python3.12/site-packages/udiskie/cli.py", line 21, in <module>
    import udiskie.mount
  File "/home/***/.local/lib/python3.12/site-packages/udiskie/mount.py", line 5, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'
```

I installed `udiskie` via `pip` on Linux Mint 21.2 with Python 3.12.1 installed manually via `make altinstall`.

```
$ pip --version
pip 23.3.1 from /home/***/.local/lib/python3.12/site-packages/pip (python 3.12)
```

**Comment by coldfix** [comment]
Hi, thanks! Will be fixed in next release. Until then, please install setuptools.
