### ISSUE TITLE
notification_command should be renamed

### ISSUE THREAD

**Issue by raffaem** [coldfix/udiskie#279]
Even with `notify: false` in `~/.config/udiskie/config.yml`, udiskie still shows notifications when a USB drive is connected/disconnected.

For example, these are the notifications send when a device is removed (obtained from `makoctl history`).

We have 3 with summaries `device_removed`, and another one with `Device removed`.

In general, I propose to remove the first three notifications, as I don't find them useful.

Otherwise, don't show them when `notify: false`.

```
{
	"type": "aa{sv}",
	"data": [
		[
			{
				"app-name": {
					"type": "s",
					"data": "udiskie"
				},
				"app-icon": {
					"type": "s",
					"data": "usb-creator"
				},
				"category": {
					"type": "s",
					"data": ""
				},
				"desktop-entry": {
					"type": "s",
					"data": ""
				},
				"summary": {
					"type": "s",
					"data": "device_removed"
				},
				"body": {
					"type": "s",
					"data": ""
				},
				"id": {
					"type": "u",
					"data": 4
				},
				"urgency": {
					"type": "y",
					"data": 1
				},
				"actions": {
					"type": "a{ss}",
					"data": {}
				}
			},
			{
				"app-name": {
					"type": "s",
					"data": "udiskie"
				},
				"app-icon": {
					"type": "s",
					"data": "usb-creator"
				},
				"category": {
					"type": "s",
					"data": ""
				},
				"desktop-entry": {
					"type": "s",
					"data": ""
				},
				"summary": {
					"type": "s",
					"data": "device_removed"
				},
				"body": {
					"type": "s",
					"data": "/dev/sda"
				},
				"id": {
					"type": "u",
					"data": 3
				},
				"urgency": {
					"type": "y",
					"data": 1
				},
				"actions": {
					"type": "a{ss}",
					"data": {}
				}
			},
			{
				"app-name": {
					"type": "s",
					"data": "udiskie"
				},
				"app-icon": {
					"type": "s",
					"data": "usb-creator"
				},
				"category": {
					"type": "s",
					"data": ""
				},
				"desktop-entry": {
					"type": "s",
					"data": ""
				},
				"summary": {
					"type": "s",
					"data": "device_removed"
				},
				"body": {
					"type": "s",
					"data": "/dev/sda1"
				},
				"id": {
					"type": "u",
					"data": 2
				},
				"urgency": {
					"type": "y",
					"data": 1
				},
				"actions": {
					"type": "a{ss}",
					"data": {}
				}
			},
			{
				"app-name": {
					"type": "s",
					"data": "udiskie"
				},
				"app-icon": {
					"type": "s",
					"data": "drive-removable-media"
				},
				"category": {
					"type": "s",
					"data": ""
				},
				"desktop-entry": {
					"type": "s",
					"data": ""
				},
				"summary": {
					"type": "s",
					"data": "Device removed"
				},
				"body": {
					"type": "s",
					"data": "device disappeared on /dev/sda"
				},
				"id": {
					"type": "u",
					"data": 1
				},
				"urgency": {
					"type": "y",
					"data": 255
				},
				"actions": {
					"type": "a{ss}",
					"data": {}
				}
			}
		]
	]
}
```

**Comment by coldfix** [comment]
Hi,


> For example, these are the notifications send when a device is removed (obtained from `makoctl history`).
> 
> We have 3 with summaries `device_removed`, and another one with `Device removed`.
> 
> In general, I propose to remove the first three notifications, as I don't find them useful.

That should normally be just one, or maybe two, notification for device removal. Looks like this might have been triggered by some special case of how udisks reports status updates to clients. The notification system needs a rework.

> Even with `notify: false` in `~/.config/udiskie/config.yml`, udiskie still shows notifications when a USB drive is connected/disconnected.
> [...]
> Otherwise, don't show them when `notify: false`.

Can you post the `config.yml` including whitespace? It should read:

```yaml
program_options:
    notify: false
```

(indentation is relevant in .yml!)

Notifications can also be disabled individually:

```yaml
notifications:
    device_removed: false
```

What does `echo $XDG_CONFIG_HOME` show? Depending on that value, your udiskie config might not have been recognized, because udiskie looks in `$XDG_CONFIG_HOME/udiskie/config.yml` if that variable is defined.

**Comment by raffaem** [comment]
Sorry for making it unclear.

With `notify: false`, the last notification, the one with `summary.data="Device Removed"`, is not triggered.

The other three notifications, the ones with `app-icon="usb-creator"`, are.

So I think it is reading the correct config file which is correctly formatted, otherwise it would not have any effect.

Anyway here is my `nvim ~/.config/udiskie/config.yml`:

```
program_options:
  # Configure defaults for command line options

  tray:             auto    # [bool] Enable the tray icon. "auto"
                            # means auto-hide the tray icon when
                            # there are no handled devices.

  menu:             flat    # ["flat" | "nested"] Set the
                            # systray menu behaviour.

  automount:        true   # [bool] Enable automatic mounting.

  notify:           true    # [bool] Enable notifications.

  password_cache:   30      # [int] Password cache in minutes. Caching is
                            # disabled by default. It can be disabled
                            # explicitly by setting it to false

  file_manager: "dolphin"
    # [string] Set program to open directories. It will be invoked
    # with the folder path as its last command line argument.

  terminal: "kitty"
    # [string] Set terminal command line to open directories. It will be
    # invoked with the folder path as its last command line argument.

  password_prompt: "builtin:gui"
    # [string|list] Set command to retrieve passwords. If specified
    # as a list it defines the ARGV array for the program call. If
    # specified as a string, it will be expanded in a shell-like
    # manner. Each string will be formatted using `str.format`. For a
    # list of device attributes, see below. The two special string values
    # "builtin:gui" and "builtin:tty" signify to use udiskie's
    # builtin password prompt.

  notify: true

  notify_command: "notify-send --icon=usb-creator --app-name=udiskie '{event}' '{device_presentation}'"
    # [string|list] Set command to be executed on any device event.
    # This is specified like `password_prompt`.

  icon_names:
    # Customize the icon set used by the tray widget. Each entry
    # specifies a list of icon names. The first installed icon from
    # that list will be used.
    media:   [drive-removable-media-usb-panel]
```

**Comment by coldfix** [comment]
Okay, that explains it I think. You might want to disable out your `notify_command` as that is executed in addition to normal notifications (it can be used to either replace builtin notification, or trigger custom commands upon actions). It is not as *"smart"* and will be called independently of the `notify: false` setting or other conditions that the builtin notification takes into account (allowing you to implement your own logic). Apparently, this is where your `usb-creator` notifications originate from:

```yaml
  notify_command: "notify-send --icon=usb-creator --app-name=udiskie '{event}' '{device_presentation}'"
```

Also, note that in your config the setting `notify: true` appears twice. Changing just one of them might not always achieve the expected effect. I recommend to remove one of these lines.

**Comment by coldfix** [comment]
I admit that the name for `notify_command` is chosen poorly and I have to improve the description. It should have been named `event_hook` or similar to distinguish it from the notification system.

**Comment by coldfix** [comment]
> Maybe we can rename that option `event_hook`, retaining the old name for backward compatibility, but having the old name almost disappear from the documentation.

Agreed, I think changing the name will be an improvement.
