### ISSUE TITLE
Change status icon: USB instead of CDROM

### ISSUE THREAD

**Issue by alejandro-perez** [coldfix/udiskie#38]
Hi,

I was wondering how complicated would it be changing the status icon from the current CDROM to a USB PENDRIVE. Nowadays, CDROM are not much used, as opposed to USB drives (HDDs, PENDRIVES...). Would it be possible to change the default icon?

Another option would be making it change depending on the kind of device attached. For instance, HDD, PENDRIVE, CDROM.

Regards

**Comment by coldfix** [comment]
Hey, I don't think, I will go for the automatic icon change according to type of inserted media, sorry (this is somewhat ambiguous anyway), so closing this for now.

**Comment by alejandro-perez** [comment]
Oh,that's completely ok. I love its current state. thanks!
