### ISSUE TITLE
setting default mount point directory

### ISSUE THREAD

**Issue by opensamba** [coldfix/udiskie#51]
hi guys, 
udiskie config problem here.
When automount with "udiskie -2" the tool use as default mount point:  /var/run/media/... 

I want to change mount point but I can't find any documentation about that.

Does anybody can help me ?

config:

```
$ cat .config/udiskie/config.yml
program_options:
 udisks_version: 2
 tray: auto
 notify: true
 file_manager: xdg-open
```

**Comment by amckinlay** [comment]
@coldfix UDISKS_FILESYSTEM_SHARED is a udev environment variable -- it doesn't work as an environment variable for `udisksd` or `udisksctl`, I tried.
