### ISSUE TITLE
Clean up if user pulls pen drive without unmounting?

### ISSUE THREAD

**Issue by feklee** [coldfix/udiskie#63]
As explained on [unix.stackexchange.com][1], I'd like unused mount points to be automatically deleted. Scenario:

 1. User plugs in pen drive. On *Ubuntu 14.04*, it gets mounted to: `/media/user/MYDRIVE`

    On Arch with a `udisks2`/`udiskie` standard installation, and with mounting to `/media/` [enabled][2], the pen drive gets mounted to: `/media/MYDRIVE`

 2. User removes pen drive. On Ubuntu, the mount point gets removed, I believe by `gvfs-udisks2-volume-monitor`. On Arch, the directory remains.

 3. User plugs in pen drive again. On Ubuntu, it gets mounted again to `/media/user/MYDRIVE`.

    On Arch a new mount point is used (name could be slightly off - have to check):

        /media/user/MYDRIVE2

[1]: http://unix.stackexchange.com/questions/198018/make-udisks2-clean-up-stale-mount-points
[2]: https://wiki.archlinux.org/index.php/Udisks#Mount_to_.2Fmedia_.28udisks2.29

**Comment by coldfix** [comment]
You're right, this has bugged me a few times as well, especially with encrypted devices, where the mapper device stays open.
My first thinking is: udiskie itself operates only with user permissions and can't clean up these mount points due to lack of permission and there is no udisks API (that I'm aware of) to do this either. This is something that should be handled by the udisks daemon. And in fact, sometimes it gets handled (on my system at least).
I will have a look, if I can locate the problem in their sources.

**Comment by feklee** [comment]
> And in fact, sometimes it gets handled (on my system at least).

*What system is that?*

Some more investigations:

 1. With XFCE on Xubuntu 14.4 *not* running, I inserted the pen drive: It was not mounted.

 2. Pulled the pen drive, then logged into XFCE. `gvfs-udisks2-volume-monitor` was started.

 3. Plugged in the pen drive, and it was mounted to: `/media/felix/TRANSCEND`

 4. Logged out of XFCE. `gvfs-udisks2-volume-monitor` was terminated

 5. Pulled the pen drive. The mount point was deleted.

I conclude: `gvfs-udisks2-volume-monitor` is actually not responsible for the clean-up. Perhaps, the Ubuntu devs patched `udisks2`.

An ugly workaround is to set up a cron job that regularly removes unused mount points in `/media`. Another workaround would be to run a script, possibly with `sudo`, that does the check every time a device is pulled. *Does `udisks2` or `udiskie` support some form of hooks?*

**Comment by coldfix** [comment]
> What system is that?

Sorry. I'm running on archlinux. The mount point cleanup works correctly in about 3/4 cases.

I did some investigation too. When running `journalctl -n20 -u udisks2 -f`, I see error messages of this form:

```
Error cleaning up mount point /run/media/thomas/STICKY5: Error unmounting: Command-line `umount -l "/run/media/thomas/STICKY5"' exited with non-zero exit status 32: umount: /run/media/thomas/STICKY5: not mounted
```

These are emitted by the udisks2 clean-up code in `udisksstate.c`. The error case prevents the trigger_change_uevent` function a few lines down the road from being called which looks like it could be the reason for not cleanuing up the device state. But I'm only guessing here. Curiously, even if deleting the offensive folders manually after pulling the drive (rmdir /media/*), they get recreated when reinserting the device again. I think we should rather forward this to the udisks2 devs.

> An ugly workaround is to set up a cron job that regularly removes unused mount points in /media. Another workaround would be to run a script, possibly with sudo, that does the check every time a device is pulled. Does udisks2 or udiskie support some form of hooks?

Yes, udisks2 generates DBus events when the device changes/disappears, but IMO the much better solution is to patch the udisks2 cleanup code.

**Comment by coldfix** [comment]
I have forwarded this issue to the [udisks bug tracker](https://bugs.freedesktop.org/show_bug.cgi?id=90174) and therefore close the issue here. Reopen if needed.

Best regards,
Thomas

**Comment by feklee** [comment]
> I have forwarded this issue to the udisks bug tracker and therefore close the issue here.

Thanks! I also was thinking about submitting a bug report, but simply I couldn't reproduce the issue anymore. Maybe it's related to a certain combination of USB pen drive and USB controller. The ones which gave me the error are currently separated by thousands of kilometers.
