### ISSUE TITLE
[feature request] getting the password for unlocking devices from an external program

### ISSUE THREAD

**Issue by chmduquesne** [coldfix/udiskie#65]
Hi,

Again, I have been reading the documentation and I don't think udiskie supports that, so apologies if it does.

I am using gnome-keyring to manage my passwords. I suppose others are using different programs.

It would be nice to be able to set udiskie to get the password for unlocking a LUKS encrypted disk from the standard output of another program. Basically, invoking:

    %s <uuid of the device>

Where %s would be replaced with a user string (in my case, I would use "gnome-keyring-query get ").

This way, people could automatically extract their passwords from the keyring.

Cheers

**Comment by chmduquesne** [comment]
By the way: x11-ssh-askpass would be a good default to replace your current prompt, if you add this feature. It's really just a window that prompts you for a password and prints it to stdout.

**Comment by coldfix** [comment]
Hey,
initially, I just used zenity for GUI password input (and systemd-ask-password on consoles) and there was a config file entry to allow using an arbitrary command instead. I then switched to an inline solution for security considerations and dropped the config file entry at the same time. I could readd that. What should the entry look like? I think, maybe a `.format` string/list, getting a device object as its parameters, so you could use it for example like this:

```
password_prompt: [/usr/lib/ssh/ssh-x11-askpass, "Enter password to unlock {.device_presentation}"]
```

What do you think?

**Comment by chmduquesne** [comment]
I think that would do it. I guess that in my case, it would be:

    password_prompt: ["gnome-keyring-query", "get", "{.device_presentation}"]

Am I right?

FYI The tool gnome-keyring-query is invoked like that:

    gnome-keyring-query get foo

This gets the passphrase associated with the entry foo (in case the keyring is locked, it will prompt the user to type the password to the keyring, otherwise it will just get it). So on my side, I guess I would remplace foo with the uuid of the device (and set up the keyring accordingly).

**Comment by coldfix** [comment]
Hey,

I upped this modification in the `prompt-config` branch, you can check it out and see if it fits your needs.

If you want to pass the UUID, you should rather use `{.id_uuid}`:

```
password_prompt: [gnome-keyring-query, get, "{.id_uuid}"]
```

There is also a short syntax

```
password_prompt: gnome-keyring-query get {.id_uuid}
```

The possible values are the properties of the `Device` class (see `udiskie.udisks2`).

**Comment by coldfix** [comment]
Almost forgot:

add this in the config file under `program_options`, i.e.:

```yaml
program_options:
  password_prompt: ...
```

**Comment by coldfix** [comment]
I merged this into master and will issue a minor release soon. Reopen, if this doesn't work for you.

**Comment by chmduquesne** [comment]
Ah, sorry, I did not have time to test this yet. I'll test when this is released on arch. Thank you!

**Comment by mmirus** [comment]
I found this issue helpful when looking up how to configure udiskie to use gnome keyring to automount encrypted devices, and thought I'd share a little additional info for anyone who finds their way here from Google.

I think
