### ISSUE TITLE
tries to connect to X and dbus during build on buildd machines

### ISSUE THREAD

**Issue by LocutusOfBorg** [coldfix/udiskie#70]
Hi again, this isn't a real issue, but I would like to understand more why the buildd reports a try to connect to X and dbus during the build
```
I: pybuild base:170: python2.7 setup.py clean 
gdk_mir_display_open
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
running clean
```

are them really required?

Another issue I'm wondering is this one:
```
WARNING:root:[Errno 2] No such file or directory: 'gtk-update-icon-cache'
```
it seems to be failing only for python3

thanks!

**Comment by coldfix** [comment]
For the first point: this is just a check to see if the dependencies are available and not necessary at all (maybe I should just remove the corresponding code section).

As for your second question: I'm not sure why this would fail on python3 only. My guess is that the `gtk-update-icon-cache` isn't available in both cases but for some reason the logger isn't set up correctly on python2 (I can take a closer look tonight or tomorrow).

BTW: gtk-update-icon-cache is executed to make sure the icons for the tray icon are available, see also the [README](https://github.com/coldfix/udiskie#gtk-icons).

**Comment by LocutusOfBorg** [comment]
>For the first point: this is just a check to see if the dependencies are available (and hence warning the >user about missing dependencies) and not actually necessary. Maybe I should just remove the >corresponding code section, what do you think?

you are upstream, I'm completely fine with some sort of warnings due to the special buildd environment :)
for me is ok, I can test it locally and then upload on the buildd machines, just I was wondering about some misbehaviour due to that warning.

>As for your second question: I'm not sure why this would fail on python3 only. My guess is that the >gtk-update-icon-cache isn't available in both cases but for some reason the logger isn't set up correctly >on python2 (I can take a closer look tonight or tomorrow).

oops my fault, I was installing the development package, thinking it was dragging the binary automatically, but this isn't the case, I need to install directly the binary package
"gtk-update-icon-cache: No theme index file."

seems actually better

>BTW: gtk-update-icon-cache is executed to make sure the icons for the tray icon are available, see also >the README.
this is why I was worried about it :)
