### ISSUE TITLE
"Device appeared" notification with action

### ISSUE THREAD

**Issue by floli** [coldfix/udiskie#72]
When a device is mounted, the notifcation contains an action that opens the file manager.

When a device appears, the notifcation does not contain an action. It would be really helpful if the notication contained an action that mounts the just appeared device.

If there are multiple partitions on that device, there could be multiple actions, or just mount all of them.

**Comment by coldfix** [comment]
Hey,
thanks for the suggestion. I'll have a look.

Usually, when automounting is enabled, it doesn't make much sense to show an action on the notification. But it sure does, when automounting is disabled. Or are you thinking about ignored devices even?

**Comment by floli** [comment]
I just learned about ignored devices from your message. Probably it doesn't make sense to show it when device is ignored. I don't use automount, so for me it's just everytime the device appeared messaged appears there could be an action.
Best Regards,....

**Comment by coldfix** [comment]
Yeah, I guess that makes sense. It shouldn't be too hard to add, but it will probably take me a bit to find some time, sorry. Also, if there are multiple partitions on your device, I doubt that it will be fun mounting more than one using the notification action buttons. This is because udiskie is currently operating in synchronous mode (this is subject to change).

**Comment by coldfix** [comment]
Hey, I added actions to the "Device added" notification and pushed the change to master. Let me know, if you have any problems.

Best regards,
Thomas

**Comment by floli** [comment]
Great! I'm right now on the Arch package (https://www.archlinux.org/packages/community/any/udiskie/) and not really with enough spare time to install it myself. But I saw, you just did a release, it usually appears quickly in Arch. I also like your configurable actions change!
I will come back if there are any problems... Thanks again!

**Comment by floli** [comment]
Just got the new version, works perfectly. Thanks again!
