### ISSUE TITLE
Exception check for missing Notify typelib.

### ISSUE THREAD

**Issue by khardix** [coldfix/udiskie#78]
When running udiskie without installed libnotify and leaving default options for the daemon in place, the daemon's setup fails when it tries to load nonexistent `gi.repository.Notify`.

Preliminary discussion on this topic in PR #77.

**Comment by coldfix** [comment]
I decided that taking different branches depending on whether the option was explicitly requested or not may be confusing and decided to handle it as in your original pull request, though I somewhat improved the error message.
