### ISSUE TITLE
should_automount is set to false for unlocked LUKS devices

### ISSUE THREAD

**Issue by coldfix** [coldfix/udiskie#80]
I just noticed that the automount hint appears to be set to false by udisks for LUKS devices. This means that they won't be automounted or even shown in the tray menu by udiskie. Therefore, the naive rule `{'should_automount': False, 'ignore': True}` is not a viable default. I disabled the rule and uploaded a bug-fix release for now.

It might be possible to add a replacement rule like

``` python
- {'should_automount': False,
   'is_luks_cleartext': False,
   'ignore': True}
```

after some more careful testing.

@mathstuf Sorry for this inconvenience. If you need this rule, you can put it in your config file for now.

**Comment by mathstuf** [comment]
Hmm. That's not the case here. It isn't set by udev, but `udiskctl dump` still shows it as `true`. What does `udevadm info $blockdevice` and `udisksctl dump` show for the device?

**Comment by coldfix** [comment]
I tried with several devices. `udevadm` doesn't show anything that caught my interest (no `UDISKS_AUTO`). `udisksctl` on the other hand shows:

```
    Drive:                      '/'
    HintAuto:                   false
    ...
    HintSystem:                 true
    ...
```

I had noticed previously that drive + HintSystem are not satisfactorily set for luks cleartext devices on my machine (at least if using udisks2), which is why the udiskie wrapper code for the device properties `is_external` and `drive` is more code than just using the values from udisks.

Judging from a look at the udisks code that sets the HintAuto flag, this is probably related to the drive not being set correctly. Here, an excerpt from `udiskslinuxblock.c`:

```c
static void
update_hints (UDisksLinuxBlock  *block,
              UDisksLinuxDevice *device,
              UDisksDrive       *drive)
{
  ...
  hint_system = TRUE;
  hint_auto = FALSE;
  ...
  if (drive != NULL)
    {
          ...
        {
          hint_system = FALSE;
          hint_auto = TRUE;
        }
    }
  ...
```

So, the best approach is probably to investigate why udisks doesn't set the drive properly (at least on my machine) and in the meantime use a custom replacement for `should_automount` like was done for `is_external` and `drive`. Will take me a while probably;)

**Comment by mathstuf** [comment]
If it helps, I'm running udisks2-2.1.6-1.fc23.x86_64.

**Comment by coldfix** [comment]
I assume, the drive for the cleartext device is set properly on your machine?

**Comment by mathstuf** [comment]
For the luks device:

```
Drive:                      '/org/freedesktop/UDisks2/drives/USB_DISK_3_2e0_070D57B36E2F7834'
HintAuto:                   true
```

But, yeah, the one which uses it as the `CryptoBackingDevice` has it wrong. But I am running the system udiskie which doesn't have the patch yet, so there's the difference.

**Comment by coldfix** [comment]
Oh, you're talking about the crypto backing device. Yeah, this one is set correctly too on my platform. Just the cleartext device behaves all wrong. Therefore, if naively using the `should_automount` flag in udiskie, the device will be unlocked, but never mounted.

**Comment by cherti** [comment]
regarding automounting of luks-devices, [this](https://github.com/coldfix/udiskie/wiki/automounting-luks-cleartext-devices) could be helpful as a workaround. I use this for my luks-disks and it works just fine for me.

**Comment by mathstuf** [comment]
I use autofs to handle my LUKS devices:

```autofs
/mnt/mapper    /etc/auto.mapper    --timeout=1,--negative-timeout=1
```

```autofs
* -fstype=auto,rw,noexec,noatime,nodev :/dev/mapper/&
```

**Comment by coldfix** [comment]
cleaning up some old issues: seems like there is nothing we can do about this, so for now can't use the `should_automount` flag in udiskie

**Comment by mathstuf** [comment]
FWIW, I do have things set up where udiskie asks for the passphrase, but it is not mounted anywhere (that is still handled by autofs). I can dig into what makes this happen if someone else needs to know.

**Comment by coldfix** [comment]
If you use this setup because udiskie didn't have the rights to mount internal devices, did you try granting the `org.freedesktop.udisks2.filesystem-mount-system` permission in addition to those recommended on the [wiki](https://github.com/coldfix/udiskie/wiki/Permissions)? Otherwise, please ignore.

**Comment by mathstuf** [comment]
No, it isn't a permission issue. I want it mounted at a custom, stable location and use `autofs` to handle that. I also want it unmounted when not in use. AFAICT, `udisks2` places everything under `/run/media/$USER` and doesn't have a `--timeout` option equivalent.
