### ISSUE TITLE
Use kernel keyring to store passphrases

### ISSUE THREAD

**Issue by mathstuf** [coldfix/udiskie#85]
It'd be nice to have a device automatically unlocked via a keyring associated with the process. Basically, put the passphrase in the kernel (with an optional timeout) when unlocking a device and try it first.

See `keyutils(7)` and `keyrings(7)`.

**Comment by coldfix** [comment]
Hey, this sounds like a nice feature. I don't have any experience with these tools so far, but it doesn't appear so hard. So far, I've shortly toyed around with the `keyctl` utility and the [keyutils](https://pypi.python.org/pypi/keyutils/) package which wraps the C API using an extension module. I think, I'd like to make this an optional dependency, but it requires a little work (not only on udiskie, but also some patches for the keyutils package), so expect it to take a bit.

Best regards, and thanks for good ideas!,
Thomas

**Comment by mathstuf** [comment]
Yeah, the idea came up when I was wrapping the C API [in Rust](https://github.com/mathstuf/rust-keyutils). My bindings use a more structured approach (e.g., methods on a `Key` struct), but the API isn't so complicated that straight calls are the worst way to do it.

**Comment by mathstuf** [comment]
Here's a script from Debian for using keyctl with cryptsetup: https://sources.debian.net/src/cryptsetup/2:1.6.6-5/debian/scripts/decrypt_keyctl/?hl=2#L2

**Comment by mathstuf** [comment]
ecryptfs: https://sources.debian.net/src/ecryptfs-utils/106-1/src/libecryptfs/key_management.c/?hl=168#L168

**Comment by coldfix** [comment]
Hey, thanks. My pull requests to the python-keyutils repository to make it usable from udiskie are already merged. I am now waiting for them to release the new version (which might be a few days or weeks, I don't know) - don't want to depend on unreleased version in the master branch.

**Comment by mathstuf** [comment]
Sweet, thanks. BTW, if you're interested more in the keyring, I found out about the keyring through [this talk](http://www.superlectures.com/guadec2013/more-secure-with-less-security), but I don't see any of the features mentioned there in the libsecret repo at all :( . Seems the keepass-based secret storage daemon I'm working on might be the first to do something like it.

**Comment by coldfix** [comment]
FYI, python-keyutils did release a new version now and I implemented password-caching in a feature branch. I will probably wait a week or two before merging this into master to see if there are any problems. You are welcome to try beforehand to check if it fits your expectations:

```
sudo pacman -R udiskie
sudo pacman -S python-virtualenv
virtualenv TESTENV
source TESTENV/bin/activate
pip install keyutils
pip install git+git://github.com/coldfix/udiskie@use-keyutils
udiskie
```

**Comment by coldfix** [comment]
**EDIT:** Sorry, fixed missing command line arguments in the above code snippet
