### ISSUE TITLE
How to use udiskie from within another python script/program?

### ISSUE THREAD

**Issue by mbusb** [coldfix/udiskie#86]
Is there any way I can use udiskie as python library? Is there any documentation regarding this?

**Comment by coldfix** [comment]
Hey,

depends on what you're trying to do. There is no particular documentation except for docstrings. You can ask for an example if you're a bit more specific. Also, I could imagine that you really want to use *udisks* not *udiskie* depending on your use case.

Note that I might change the internal API between versions.

**Comment by coldfix** [comment]
Hey, I'm closing this issue for now. Feel free to reopen if you still need help. In that case, please describe your use case more precisely.
