### ISSUE TITLE
I can´t see notifications

### ISSUE THREAD

**Issue by semeion** [coldfix/udiskie#88]
I can´t see notifications when i insert/remove a pendrive.

errors message in console:

/usr/bin/udiskie:9: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  load_entry_point('udiskie==1.3.2', 'console_scripts', 'udiskie')()
sys:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
not adding /org/freedesktop/UDisks2/block_devices/sdc: unhandled device
mounted /org/freedesktop/UDisks2/block_devices/sdc1 on /media/KINGSTON
Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

**Comment by semeion** [comment]
I am using Openbox with Arch Linux x86_64. The udiske package is from official repository.

How fix it?

Thanks in advance

**Comment by coldfix** [comment]
Do you have a notification daemon installed, e.g. xfce4-notifyd / dunst / ...?

**Comment by semeion** [comment]
No, i don´t. I will install it. Thank you!

**Comment by semeion** [comment]
Amazing program, thanks for this nice work!

Do you know if is possible make udiskie start only when the pendrive is inserted?

**Comment by coldfix** [comment]
Hey, no problem.

You can configure udiskie to show the icon only if some device is present. If that's what you want start udiskie with `--smart-tray` or put the line `tray: auto` in your `~/.config/udiskie/config.yml` file.

If you really want to *start udiskie* only as soon as some device is inserted: you could try doing that with udev rules. But I doubt that makes a lot of sense, in that case you are probably looking for a mounting solution using only udev rules anyway?

**Comment by semeion** [comment]
wow, it is cool! thank you! :D

**Comment by semeion** [comment]
Is working like a charm. I loved this program.

**Comment by coldfix** [comment]
Great:) Closing this issue. Feel free to report any further problems you encounter.
