### ISSUE TITLE
some new, non-fatal messages in tty at startup

### ISSUE THREAD

**Issue by thunderrd** [coldfix/udiskie#89]
Hey coldfix, I'm back to you with a little information and some new messages in the tty at startup.  Running gentoo, startup of udiskie outputs the following.  The python guys on IRC recommended a rebuild of pygobject, which I did, but the message persists.  There does not seem to be any loss of functionality, but it looks like a message for you to fix some code someplace: [?]

thunderrd@Q6600:~$ udiskie -n -s -2 &
[1] 2390
thunderrd@Q6600:~$ /usr/lib64/python2.7/site-packages/udiskie/prompt.py:11: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/lib64/python2.7/site-packages/udiskie/cli.py:319: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify

**Comment by coldfix** [comment]
Hey, I have already fixed that a few days ago in the most recent commit on master. This will probably be released in a week or two with other changes.

Thanks for your report anyway!

**Comment by thunderrd** [comment]
OK then, done.
Thanks for the attention.
-tr
