### ISSUE TITLE
Mounting using UUID

### ISSUE THREAD

**Issue by fmitha** [coldfix/udiskie#90]
Is it possible to mount using the UUID reported from `blkid`? I presume this can be passed an an option to `python-udiskie`. `blkid` reports my Passport USB drive as:

    /dev/sde1: LABEL="My Passport" UUID="4E1AEA7B1AEA6007" TYPE="ntfs" PARTUUID="5b037298-01"

So I think something in the general region of

    udiskie-mount -o "id_uuid:4E1AEA7B1AEA6007"

should probably work, but I don't know what the exact syntax should be.

From the man page, it looks like I could add this to the `config.yml` file, using
the `mount_options` option, but I'd like to specify it on the command line, at least for now.

I'm using the Debian `python-udiskie` package, version `1.3.2-1`.

Thanks for writing `python-udiskie`. I was wondering how to use `udisks2`, and then stumbled on your program.

Regards, Faheem Mitha

**Comment by coldfix** [comment]
Currently not. But this requires just a minor change and will be no problem to include it in the next version. All suggestions welcome.

**Comment by coldfix** [comment]
By the way, you should be able to mount as `udiskie-mount /dev/disk/by-uuid/UUID` for now. I will sleep over whether to support mountinong by UUID directly and how to specify it.

**Comment by fmitha** [comment]
The command `udiskie-mount /dev/disk/by-uuid/UUID` works, thank you. It's probably worth documenting that somewhere, even though I guess it's nothing to do with `udisk2`.
