### ISSUE TITLE
Debian bug: python3-udiskie/python-udiskie do not start

### ISSUE THREAD

**Issue by fmitha** [coldfix/udiskie#91]
https://bugs.debian.org/806560 is currently open in the Debian bug tracker; I don't know if you have seen it. It doesn't affect me personally, I use the command line. But I didn't know if you had seen it.
If you aren't already subscribed to the Debian bug reports for this package, consider adding yourself.

Regards, Faheem Mitha

**Comment by coldfix** [comment]
Oh thanks. No, I'm not subscribed yet. Looks to me like they are using GTK2 which doesn't work for the tray. Thanks for forwarding this here.

**Comment by coldfix** [comment]
(That problem should be fixed in the new release.)
