### ISSUE TITLE
Don't run tests for PasswordCache when keyutils are not available

### ISSUE THREAD

**Issue by khardix** [coldfix/udiskie#95]
The testsuite currently assumes that the keyutils are installed (even they are specified as extras_require), and thus it fails on ImportErrors when the module is not available.

**Comment by coldfix** [comment]
Humm, true. To be fair, I don't think you can really call it a test suite:D - there are barely any tests at all, and I didn't expect anyone to actually run them. How do you start your tests? Can't you just specify a list with which tests you'd like to run - depending on your environment?

**Comment by khardix** [comment]
Well, I just run `python setup.py test`, and so far I was unable to find out how to pass the test specification to setuptools.

As for running them -- as a packager, when the package has any tests, I should run them, so I do ☺.

**Comment by coldfix** [comment]
You can run:

```
python setup.py test -s test.test_match

# or just:

python -m unittest -v test.test_match
```

The other test fails if you don't have keyutils installed, which is kind of the point. Do you think, there should be a separate module that selects which tests do make sense to run depending on which dependencies are satisfied?

**Comment by khardix** [comment]
OK, it will do for now.

I don't know about separate module, but if you have optional dependencies, it would make sense to me to mark (somehow) the tests as "Test for optional feature X" and automatically skip them if the feature X is not present (i.e. due to missing dependencies). The big question is if the unittest module is able to do such autoselection.

Personally, I use [pytest](http://pytest.org/latest/index.html "pytest: helps you write better programs") for testing, and it supports [such selections](http://pytest.org/latest/skipping.html "Skip and xfail: dealing with tests that can not succeed").

**Comment by coldfix** [comment]
> Personally, I use pytest for testing, and it supports such selections.

Interesting - thanks. I will keep that in mind - and notify you if I ever come to build a real set of tests.
