### ISSUE TITLE
error at startup since 1.4.0

### ISSUE THREAD

**Issue by tegularius** [coldfix/udiskie#97]
When starting udiskie I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/udiskie/cli.py", line 253, in _start_async_tasks
    self.udisks = yield get_backend(self.options['udisks_version'])
TypeError: new_for_bus() got an unexpected keyword argument 'user_data'
```

Version 1.3.2 worked after reinstalling, 1.4.0, 1.4.6 and current git did not. (I tried pip as well)
I am using Slackware64-current with python-2.7.11 and installed it via slackware-slackbuild (sbopkg).
I have udisks-1.0.5 and udisks2-2.1.5 installed.

**Comment by coldfix** [comment]
Hey, thanks.

This problem doesn't exist on my slack VM. Can you post your version of pygobject? Mine is 3.10.2.

Can you check whether the branch `fix-slack` fixes the problem:

    pip install git+git://github.com/coldfix/udiskie@fix-slack

**Comment by tegularius** [comment]
I'm using the same version of pygobject3. fix-slack makes the problem disappear, everything (well, auto-mounting an encrypted usb-stick) works.

**Comment by coldfix** [comment]
Okay. What's your glib/gio version?

I'll do a new release with the patch shortly.

**Comment by tegularius** [comment]
I have glib2-2.46.2 with gio-2.0 (4600?).
