### ISSUE TITLE
[Request] Key to temporarily disable automounting

### ISSUE THREAD

**Issue by Moredread** [coldfix/udiskie#98]
It be great if there was a (configurable) option to temporally disable automounting while holding a specified key, e.g. Shift, like it is used in Windows to suppress autoexecution of an inserted medium.

**Comment by coldfix** [comment]
Good idea:)
I'll see whether there is an easy way to achieve this.

**Comment by somini** [comment]
This should also be exposed in the tray interface.
It's very useful when formatting partitions, for example.

**Comment by coldfix** [comment]
Agreed, I'll get on it this weekend.

**Comment by coldfix** [comment]
Okay, I added an entry in the systray menu. So far no hotkey, though. Give me a note and repoen if you prefer a hotkey and which Gio object can be used to set one up.
